/**
 * Pre-deploy codegen: reads the Matomo fleet registry and generates
 * `src/upstreams.generated.ts` with the appId → matomoCloudHost mapping.
 *
 * Run via `pnpm run gen:upstreams` before `wrangler deploy`.
 * The generated file is .gitignored — it is rebuilt on every deploy.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REGISTRY_PATH = join(
  __dirname,
  "..",
  "..",
  "..",
  "packages",
  "ontology",
  "analytics",
  "matomo-fleet.registry.yaml",
);
const OUTPUT_PATH = join(__dirname, "..", "src", "upstreams.generated.ts");

interface FleetRegistrySite {
  appId: string;
  matomoCloudHost?: string;
  status?: string;
}

interface FleetRegistry {
  sites?: FleetRegistrySite[];
}

// Minimal YAML parser for the fleet registry (avoids adding js-yaml dependency).
// The registry YAML is simple enough to parse with a targeted approach.
function parseFleetRegistry(raw: string): FleetRegistry {
  const lines = raw.split("\n");
  const sites: FleetRegistrySite[] = [];
  let inSites = false;
  let currentSite: FleetRegistrySite | null = null;

  for (const line of lines) {
    const trimmed = line.trimEnd();

    if (trimmed.startsWith("sites:")) {
      inSites = true;
      continue;
    }

    if (inSites && trimmed && !trimmed.startsWith(" ") && !trimmed.startsWith("-")) {
      inSites = false;
      if (currentSite) sites.push(currentSite);
      currentSite = null;
      continue;
    }

    if (!inSites) continue;

    if (trimmed.startsWith("  - appId:")) {
      if (currentSite) sites.push(currentSite);
      currentSite = { appId: trimmed.slice("  - appId:".length).trim().replace(/["']/g, "") };
      continue;
    }

    if (currentSite && trimmed.startsWith("    matomoCloudHost:")) {
      currentSite.matomoCloudHost = trimmed
        .slice("    matomoCloudHost:".length)
        .trim()
        .replace(/["']/g, "");
      continue;
    }

    if (currentSite && trimmed.startsWith("    status:")) {
      currentSite.status = trimmed.slice("    status:".length).trim().replace(/["']/g, "");
      continue;
    }
  }

  if (currentSite) sites.push(currentSite);
  return { sites };
}

const raw = readFileSync(REGISTRY_PATH, "utf8");
const registry = parseFleetRegistry(raw);

const upstreams: Record<string, string> = {};
for (const site of registry.sites ?? []) {
  if (site.status === "active" && site.appId && site.matomoCloudHost) {
    upstreams[site.appId] = site.matomoCloudHost;
  }
}

const content = `// GENERATED. Do not edit this file manually.
// Source: packages/ontology/analytics/matomo-fleet.registry.yaml
// Regenerate via: pnpm run gen:upstreams
export const UPSTREAMS: Record<string, string> = ${JSON.stringify(upstreams, null, 2)};
`;

writeFileSync(OUTPUT_PATH, content, "utf8");
console.log(
  `[gen:upstreams] Generated ${OUTPUT_PATH} with ${Object.keys(upstreams).length} upstream(s)`,
);
