/*
<MODULE_CONTRACT>
<purpose>Re-export deploy command from @gogol/site-kernel-deploy.</purpose>
<non-goals>
  <item>Do not implement logic locally — this file is a thin proxy.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
export { runClientExport } from "@gogol/site-kernel-deploy";
