/*
 * GENERATED CODE — DO NOT EDIT.
 * Generated by scripts/gen-event-names.ts from packages/ontology/growth/events/*.yaml
 * Run `pnpm --filter @warpgogol/growth run codegen:event-names` to regenerate.
 */
export const EVENT_NAMES = [
  "contact-submit",
  "contact.email_click",
  "contact.form_submit",
  "contact.phone_click",
  "contact.route_click",
  "contact.whatsapp_click",
  "cta-click",
  "donation-confirmed",
  "donation-form-start",
  "donation-form-submit",
  "donation-intent",
  "form-error",
  "form-start",
  "form-submit",
  "outbound-click",
  "page-view",
  "passport-view",
  "star-map-navigate",
] as const;

export type EventName = (typeof EVENT_NAMES)[number];
