{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>S-2 layout-global script orchestrator. Conditionally loads page features based on DOM presence.</purpose>
<non-goals>
  <item>Do not manage component-specific behaviour — that belongs in S-1 scripts inside each component.</item>
  <item>Do not import heavy dependencies unconditionally.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Autogenerated file.</item>
  <item>LH-02: guard the dynamic import behind a querySelector for orchestrated elements.</item>
</CHANGE_SUMMARY>
*/

void (async () => {
  if (document.readyState === "loading") {
    await new Promise((resolve) => document.addEventListener("DOMContentLoaded", resolve));
  }

  // Reduced motion: the orchestration module honors prefers-reduced-motion and
  // gates every effect it runs on that setting. This launcher only decides
  // whether to load that module at all; it starts no effects itself.
  // LH-02 DOM guard: only pull in the orchestration module when the page actually
  // contains an element it manages — links to harden, LordIcons, or motion hooks.
  // Pages with none of these skip the dynamic import entirely.
  const ORCHESTRATED_SELECTOR =
    "a[href], lord-icon, .js-inline-number, [data-motion-reveal], [data-parallax-speed], [data-motion-stagger], [data-live-photo], video[data-video-player]";
  if (!document.querySelector(ORCHESTRATED_SELECTOR)) return;

  const { runStandardLayoutOrchestration } = await import("@warpgogol/werkstatt-site/share/scripts");

  // Read orchestrator config from site context (injected by server)
  const siteConfig = (window as any).__SITE_CONFIG ?? {};
  const orchestrator = siteConfig.orchestrator ?? {};
  const connection = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection;
  const deviceMemory = (navigator as Navigator & { deviceMemory?: number }).deviceMemory ?? 4;
  const hardwareConcurrency = navigator.hardwareConcurrency ?? 4;
  const canRunSmoothScroll =
    !connection?.saveData && deviceMemory >= 4 && hardwareConcurrency >= 4;

  await runStandardLayoutOrchestration({
    counters: orchestrator.counters ?? false,
    inlineNumbers: orchestrator.inlineNumbers ?? false,
    reveal: orchestrator.reveal ?? false,
    parallax: orchestrator.parallax ?? false,
    stagger: orchestrator.stagger ?? false,
    // RFC-0202: living-photos runtime is self-gating on [data-live-photo][data-trigger]
    // inside runStandardLayoutOrchestration — zero cost when the page has no living photos.
    livePhotos: orchestrator.livePhotos ?? true,
    // RFC-0210: feature-video player runtime is self-gating on video[data-video-player]
    // inside runStandardLayoutOrchestration — zero cost when the page has no feature video.
    videoPlayers: orchestrator.videoPlayers ?? true,
    // RFC-0205: Lenis smooth scroll is opt-in to avoid loading the 17 KB bundle on every page.
    // LH-08: additionally gate Lenis on saveData/deviceMemory/hardwareConcurrency.
    smoothScroll: (orchestrator.smoothScroll ?? false) && canRunSmoothScroll,
  });
})();
