/*
<MODULE_CONTRACT>
<purpose>
RFC-0557: workpiece.imports.validate — scans all generated .ts/.mjs/.astro files
in the materialized workpiece's tools/ and src/ directories for @warpgogol/* and
@warpgogol/* imports, and verifies each import resolves from root node_modules
(symlink existence check). Integrated into SITES_BUILD_PREPARE_PIPELINE as the
first step.
</purpose>
<non-goals>
  <item>Does not validate template imports — that is template.imports.validate.</item>
  <item>Does not validate files generated by SITES_BUILD_PREPARE_PIPELINE generators — only materialized files are scanned.</item>
  <item>Does not run pnpm install — lockfile integrity is checked by template.imports.validate.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0557: initial implementation of workpiece.imports.validate.</item>
</CHANGE_SUMMARY>
*/

import { readFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { parse as parseYaml } from "yaml";
import { collectFiles, fileExists } from "@warpgogol/werkstatt-site/share/fs";
import type {
  CheckResult,
  Diagnostic,
  KernelCommandInput,
  KernelCommandResult,
  KernelRuntimeContext,
} from "@warpgogol/werkstatt/kernel";
import { diagnosticsResult } from "./result-helpers.ts";
import { extractWorkspaceImports } from "./template-imports-validate.ts";

const COMMAND = "workpiece.imports.validate";

export interface WorkpieceImportsValidateData extends CheckResult {
  site: string;
  filesScanned: number;
  importsFound: Array<{
    package: string;
    file: string;
    line: number;
  }>;
  unresolved: Array<{
    package: string;
    file: string;
    line: number;
    error: string;
  }>;
}

function readFlag(input: KernelCommandInput, name: string): string | undefined {
  const direct = input.flags[name];
  if (typeof direct === "string") return direct;
  return undefined;
}

export async function runWorkpieceImportsValidate(
  input: KernelCommandInput,
  context: KernelRuntimeContext,
): Promise<KernelCommandResult<WorkpieceImportsValidateData>> {
  const diagnostics: Diagnostic[] = [];
  const { workspaceRoot } = context;

  // ── Resolve --site flag ─────────────────────────────────────────────────────
  const site = readFlag(input, "site");
  if (!site) {
    diagnostics.push({
      ruleId: "WORKPIECE-IMPORTS-01",
      severity: "error",
      message: "--site <name> is required.",
      fixHint: "Pass --site <system-id> to specify which workpiece to validate.",
    });
    return diagnosticsResult(
      COMMAND,
      diagnostics,
    ) as KernelCommandResult<WorkpieceImportsValidateData>;
  }

  // ── Resolve workpiece directory ─────────────────────────────────────────────
  const workpieceDirOverride = readFlag(input, "workpiece-dir");
  let workpieceDir: string;
  if (workpieceDirOverride) {
    workpieceDir = join(workspaceRoot, workpieceDirOverride);
  } else {
    // Resolve from registry: find the current mission for this site
    const missionsDir = join(workspaceRoot, "missions");
    if (!(await fileExists(missionsDir))) {
      diagnostics.push({
        ruleId: "WORKPIECE-IMPORTS-01",
        severity: "error",
        message: `No missions directory found at ${missionsDir}.`,
        fixHint: "Ensure a mission is open for this site before running build.prepare.",
      });
      return diagnosticsResult(
        COMMAND,
        diagnostics,
      ) as KernelCommandResult<WorkpieceImportsValidateData>;
    }

    // Find mission directory containing a workpiece for this site
    // Also search archive subdirectories — release.prepare runs on closed missions
    const { readdir } = await import("node:fs/promises");
    let found = false;
    let missionWorkpieceDir: string | null = null;
    const matchingMissions: string[] = [];
    const searchDirs = [missionsDir];
    for (const state of ["archive/closed", "archive/aborted"]) {
      searchDirs.push(join(missionsDir, state));
    }
    for (const searchDir of searchDirs) {
      if (!(await fileExists(searchDir))) continue;
      let entries;
      try {
        entries = await readdir(searchDir, { withFileTypes: true });
      } catch {
        continue;
      }
      for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        // Skip the "archive" directory itself when scanning missionsDir
        if (entry.name === "archive") continue;
        const candidate = join(searchDir, entry.name, "workpiece");
        if (await fileExists(candidate)) {
          let matches = false;
          // Check mission.yaml for systemId (canonical mission metadata)
          const missionFile = join(searchDir, entry.name, "mission.yaml");
          if (await fileExists(missionFile)) {
            try {
              const missionRaw = await readFile(missionFile, "utf-8");
              const missionData = parseYaml(missionRaw) as { systemId?: string };
              if (missionData.systemId === site) matches = true;
            } catch {
              // continue to fallback
            }
          }
          // Fallback: check system.json for id (legacy convention)
          if (!matches) {
            const systemFile = join(searchDir, entry.name, "system.json");
            if (await fileExists(systemFile)) {
              try {
                const systemRaw = await readFile(systemFile, "utf-8");
                const systemData = JSON.parse(systemRaw) as { id?: string };
                if (systemData.id === site) matches = true;
              } catch {
                // continue
              }
            }
          }
          if (matches) matchingMissions.push(join(searchDir, entry.name));
        }
      }
    }

    if (matchingMissions.length > 0) {
      // Pick the latest mission by directory name (mission IDs are sequential)
      matchingMissions.sort();
      const latest = matchingMissions[matchingMissions.length - 1]!;
      missionWorkpieceDir = join(latest, "workpiece");
      found = true;
    }

    if (!found || !missionWorkpieceDir) {
      diagnostics.push({
        ruleId: "WORKPIECE-IMPORTS-01",
        severity: "error",
        message: `No current mission workpiece found for site '${site}'.`,
        fixHint: `Open a mission for site '${site}' via mission.open, or pass --workpiece-dir to specify the path.`,
      });
      return diagnosticsResult(
        COMMAND,
        diagnostics,
      ) as KernelCommandResult<WorkpieceImportsValidateData>;
    }
    workpieceDir = missionWorkpieceDir;
  }

  if (!(await fileExists(workpieceDir))) {
    diagnostics.push({
      ruleId: "WORKPIECE-IMPORTS-01",
      severity: "error",
      message: `Workpiece directory does not exist: ${workpieceDir}.`,
      fixHint: "Run mission.materialize to generate the workpiece before validating.",
    });
    return diagnosticsResult(
      COMMAND,
      diagnostics,
    ) as KernelCommandResult<WorkpieceImportsValidateData>;
  }

  // ── Scan workpiece files ────────────────────────────────────────────────────
  const scanDirs = [
    { dir: join(workpieceDir, "tools"), extensions: [".ts"] },
    { dir: join(workpieceDir, "src"), extensions: [".ts", ".mjs", ".astro"] },
  ];

  const allImports: Array<{ package: string; file: string; line: number }> = [];
  let filesScanned = 0;

  for (const { dir, extensions } of scanDirs) {
    if (!(await fileExists(dir))) continue;
    const files = await collectFiles(dir, {
      extensions,
      ignore: (name) => name.startsWith("-") || name.startsWith("old-") || name === "node_modules",
    });
    for (const absPath of files) {
      let content: string;
      try {
        content = await readFile(absPath, "utf-8");
      } catch {
        continue;
      }
      filesScanned++;
      const relPath = relative(workpieceDir, absPath).replace(/\\/g, "/");
      const imports = extractWorkspaceImports(content, relPath);
      allImports.push(...imports);
    }
  }

  // ── Check each import resolves from workpiece node_modules ──────────────────
  const unresolved: Array<{ package: string; file: string; line: number; error: string }> = [];

  for (const imp of allImports) {
    const nodeModulesPath = join(workpieceDir, "node_modules", imp.package);
    const exists = await fileExists(nodeModulesPath);
    if (!exists) {
      unresolved.push({
        ...imp,
        error: `Package '${imp.package}' not found in workpiece node_modules`,
      });
      diagnostics.push({
        ruleId: "WORKPIECE-IMPORTS-01",
        severity: "error",
        file: imp.file,
        line: imp.line,
        message: `Import of '${imp.package}' in ${imp.file}:${imp.line} cannot be resolved from workpiece node_modules.`,
        fixHint: `Add "${imp.package}": "workspace:*" to workpiece package.json dependencies and run pnpm install.`,
      });
    }
  }

  const result = diagnosticsResult(COMMAND, diagnostics);
  const data: WorkpieceImportsValidateData = {
    command: COMMAND,
    status: result.data?.status ?? "pass",
    diagnostics: result.data?.diagnostics ?? [],
    summary: result.data?.summary ?? { error: 0, warning: 0, info: 0 },
    site,
    filesScanned,
    importsFound: allImports,
    unresolved,
  };

  return {
    data,
    exitCode: result.exitCode,
    summary: result.summary,
  };
}
