// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: 6f36c5c4662df05e2ee46373c7ebafc7c30198064cd0a898f5645b3bd323426b
// Source: packages/ui/src/components/currency-selector/currency-selector-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface CurrencySelectorComponentContent {
  label: string;
  currencies: {
    code: string;
    label: string;
  }[];
}
