/*
<MODULE_CONTRACT>
<purpose>Facilitates the definition and registration of content collections for structured data access.</purpose>
<non-goals>
  <item>Do not handle raw content parsing outside defined collections.</item>
  <item>Do not manage transport or configuration orchestration for content delivery.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
<item>Annotate Compass scaffolding to enhance code navigation and maintainability.</item>
</CHANGE_SUMMARY>
*/

// [DNA-04][DNA-10] Content collections are the ONLY source of typed, validated content.
// Register all collections here. Export their types for page routes to use.
// Scaffold generated by onboarding.scaffold (RFC-0030 / DNA-36).

import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";
import { markdownCollectionLoader } from "@warpgogol/werkstatt-site/share/astro/loaders";
import { fsDataCollectionLoader } from "@warpgogol/werkstatt-site/content-source";
import { pbpCollections } from "@warpgogol/werkstatt-site/pbp/astro";
import { createFaqCollection } from "@warpgogol/werkstatt-site/faq/astro";
import { toDataEntryId } from "@warpgogol/werkstatt-site/share/content";

const system = defineCollection({
  loader: glob({
    pattern: "system.md",
    base: "src/content",
    generateId: () => "system",
  }),
  schema: z.object({}).loose(),
});

// Loads all .md files from src/content/pages/ as the "pages" collection.
const pages = defineCollection({
  loader: markdownCollectionLoader("src/content/pages"),
  schema: z.object({}).loose(),
});

const prose = defineCollection({
  loader: markdownCollectionLoader("src/content/prose"),
  schema: z.object({}).loose(),
});

const site = defineCollection({
  loader: markdownCollectionLoader("src/content/site"),
  schema: z.object({}).loose(),
});

const navigation = defineCollection({
  loader: markdownCollectionLoader("src/content/navigation"),
  schema: z.object({}).loose(),
});

// Loads person records from src/content/people/{lang}/ as the "people" collection (RFC-0200).
const people = defineCollection({
  loader: fsDataCollectionLoader({
    base: "src/content/people",
    generateId: (entry) => toDataEntryId(entry),
  }),
  schema: z.object({}).catchall(z.any()),
});

const faq = createFaqCollection();

export const collections = {
  ...pbpCollections,
  system,
  pages,
  prose,
  site,
  navigation,
  people,
  ...faq,
};
