/*
<MODULE_CONTRACT>
<purpose>Facilitates language-based redirection for incoming requests, enhancing user experience by serving localized content.</purpose>
<non-goals>
  <item>Do not handle language content parsing or management.</item>
  <item>Do not implement transport or configuration orchestration for middleware.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Annotate Compass scaffolding to clarify architectural intent and responsibilities.</item>
</CHANGE_SUMMARY>
*/

// [DNA-02][RFC-0010] Language redirect middleware.
// Runs on every request. Redirects non-root paths to /{lang}/ based on Accept-Language.
// Root / path is SKIPPED — client-side detection in index.astro handles it for static builds.
// Scaffold generated by onboarding.scaffold (RFC-0030 / DNA-36).

import { createLanguageRedirectMiddleware } from "@warpgogol/werkstatt-site/share/middleware";

// supportedLangs starts with just the default language. Add more locales here
// (and create matching src/content/pages/<lang>/ trees) as the site goes multilingual.
export default createLanguageRedirectMiddleware({
  supportedLangs: ["{{DEFAULT_LANG}}"],
  defaultLang: "{{DEFAULT_LANG}}",
});
