// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: 7b2fd99fc9b97925a5334dacd472e5bab65b8ced0dc1672784a12f16171bf0dd
// Source: packages/ui/src/components/lang-switcher/lang-switcher-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface LangSwitcherComponentContent {
  switchAriaLabel: string;
}
