// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec site-kernel run props.types.generate
// sourceHash: 6c06e9f70f00318568c129a4f226994f2027cfe18c392335d69e69d96113decc
// Source: packages/ui/src/components/breadcrumbs/breadcrumbs-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface BreadcrumbsComponentContent {
  homeLabel: string;
  navAriaLabel: string;
}
