/*
<MODULE_CONTRACT>
<purpose>
TypeScript companion to @warpgogol/tokens — exports TOKEN_NAMES (a readonly const
tuple of every --ds-* custom property defined in tokens.css) and a DesignToken
type alias for safe usage in validators, style tooling, and tests.
DEFAULT values are those of the Warpgogol studio site (apps-todo/main).
</purpose>
<non-goals>
  <item>Do not import or bundle the CSS file — this module is TS-only.</item>
  <item>Do not export token VALUES — values live exclusively in tokens.css.</item>
  <item>Do not include app-specific override tokens (e.g. --ds-z-*).</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Wave 6 (RFC-0023): Initial creation alongside tokens.css extraction.</item>
</CHANGE_SUMMARY>
*/

// ---------------------------------------------------------------------------
// Token names — mirrors src/tokens.css :root {} block
// ---------------------------------------------------------------------------

export const TOKEN_NAMES = [
  // RGB primitives
  "--ds-rgb-white",
  "--ds-rgb-black",
  "--ds-rgb-brand-1",
  "--ds-rgb-brand-2",
  // Spacing
  "--ds-space-0",
  "--ds-space-1xs",
  "--ds-space-1",
  "--ds-space-2",
  "--ds-space-3",
  "--ds-space-4",
  "--ds-space-5",
  "--ds-space-6",
  "--ds-space-7",
  "--ds-space-8",
  "--ds-space-2xs-35",
  "--ds-space-md-20",
  "--ds-space-3xs",
  "--ds-space-2xs-plus",
  "--ds-space-3xl",
  "--ds-space-px",
  "--ds-space-10",
  "--ds-space-12",
  "--ds-space-16",
  "--ds-space-18",
  "--ds-space-20",
  "--ds-space-portrait-offset",
  "--ds-space-portrait-offset-md",
  "--ds-space-portrait-offset-sm",
  "--ds-space-sm-625",
  "--ds-space-sm-875",
  "--ds-space-sm-90",
  "--ds-space-xs-60",
  "--ds-space-sm-65",
  "--ds-space-2xs-45",
  "--ds-space-process-side-min",
  "--ds-space-process-side-max",
  "--ds-space-em-40",
  "--ds-space-em-50",
  "--ds-space-em-80",
  "--ds-space-em-100",
  // Typography — font stacks
  "--ds-font-body",
  "--ds-font-heading",
  "--ds-font-mono",
  "--ds-font-weight-bold",
  "--ds-font-weight-medium",
  // Typography — text sizes
  "--ds-text-0",
  "--ds-text-1",
  "--ds-text-2",
  "--ds-text-3",
  "--ds-text-3-compact",
  "--ds-text-4",
  "--ds-text-2xl",
  "--ds-text-3xl",
  "--ds-text-3xl-sm",
  "--ds-text-4xl",
  "--ds-text-5xl",
  "--ds-text-5",
  "--ds-text-6",
  "--ds-text-lg",
  "--ds-text-xl",
  // Font size aliases
  "--ds-font-size-lg",
  "--ds-font-size-xl",
  "--ds-font-size-4xl",
  "--ds-text-sm",
  "--ds-text-sm-85",
  "--ds-text-sm-80",
  "--ds-text-sm-92",
  "--ds-text-sm-925",
  "--ds-text-xs",
  "--ds-text-xs-70",
  "--ds-text-xs-75",
  "--ds-text-2xs",
  "--ds-text-em-80",
  "--ds-text-em-85",
  "--ds-text-lg-plus",
  "--ds-text-base-plus",
  "--ds-text-base",
  // Typography — line heights
  "--ds-line-height-md",
  "--ds-line-height-sm",
  "--ds-line-height-snug",
  "--ds-line-height-compact",
  "--ds-line-height-tight",
  "--ds-line-height-xl",
  "--ds-line-height-lg",
  "--ds-line-height-body",
  "--ds-line-height-heading",
  "--ds-line-height-normal",
  "--ds-line-height-relaxed",
  // Typography — letter spacing
  "--ds-tracking-md",
  "--ds-tracking-xl",
  "--ds-tracking-wide",
  "--ds-tracking-tight",
  // Border radius
  "--ds-radius-1",
  "--ds-radius-2",
  "--ds-radius-3",
  "--ds-radius-xs",
  "--ds-radius-md",
  "--ds-radius-round",
  "--ds-radius-full",
  "--ds-radius-pill",
  "--ds-radius-sm",
  "--ds-radius-sm-plus",
  "--ds-radius-lg",
  // Borders
  "--ds-border-1",
  "--ds-border-2",
  "--ds-border-3",
  "--ds-border-diagram-line",
  // Motion — durations
  "--ds-duration-1",
  "--ds-duration-2",
  "--ds-duration-3",
  "--ds-duration-4",
  "--ds-duration-xxs",
  "--ds-duration-lg",
  "--ds-duration-fast",
  "--ds-duration-medium",
  "--ds-duration-slow",
  "--ds-duration-quote-float",
  "--ds-duration-hero-float",
  "--ds-duration-portrait-float",
  "--ds-duration-rotate-slow",
  "--ds-duration-waitlist-sway",
  // Motion — easing
  "--ds-ease-smooth",
  "--ds-ease-standard",
  "--ds-ease-biome",
  // Geometry
  "--ds-angle-tilt",
  "--ds-angle-tilt-positive",
  // Effects
  "--ds-blur-xs",
  "--ds-blur-sm",
  "--ds-blur-md",
  "--ds-blur-lg",
  "--ds-filter-quote-image",
  "--ds-filter-saturate-105",
  // Colors — base
  "--ds-color-bg",
  "--ds-color-surface",
  "--ds-color-surface-elevated",
  "--ds-color-surface-inverse",
  "--ds-color-surface-raised",
  "--ds-color-surface-hover",
  "--ds-color-surface-glass",
  "--ds-color-surface-glass-hover",
  "--ds-color-surface-glass-dark",
  "--ds-color-surface-glass-strong",
  // Colors — text
  "--ds-color-text",
  "--ds-color-text-legacy",
  "--ds-color-text-muted",
  "--ds-color-text-primary",
  "--ds-color-text-secondary",
  "--ds-color-text-quiet",
  "--ds-color-text-quiet-inverse",
  "--ds-color-text-inverse",
  "--ds-color-text-inverse-84",
  "--ds-color-text-inverse-60",
  "--ds-color-text-soft-on-dark",
  "--ds-color-text-on-dark-84",
  // Colors — brand
  "--ds-color-primary",
  "--ds-color-primary-dark",
  "--ds-color-secondary",
  "--ds-color-accent",
  "--ds-color-accent-contrast",
  "--ds-color-accent-hover",
  "--ds-color-accent-legacy",
  "--ds-color-accent-soft",
  "--ds-color-accent-soft-weak",
  "--ds-color-accent-700",
  "--ds-color-accent-focus",
  "--ds-color-accent-focus-strong",
  "--ds-color-accent-ai",
  "--ds-color-accent-ai-glow",
  "--ds-color-accent-bfsg",
  "--ds-color-accent-bfsg-glow",
  // Colors — semantic state
  "--ds-color-success",
  "--ds-color-success-12",
  "--ds-color-success-36",
  "--ds-color-success-dark",
  "--ds-color-success-solid",
  "--ds-color-success-bright-12",
  "--ds-color-success-bright-36",
  "--ds-color-success-bright-60",
  "--ds-color-success-border",
  "--ds-color-success-soft",
  "--ds-color-warning-strong",
  "--ds-color-status",
  "--ds-color-danger",
  "--ds-color-danger-bright",
  "--ds-color-danger-soft",
  "--ds-color-error-border",
  "--ds-color-error-soft",
  "--ds-color-info",
  // Colors — borders
  "--ds-color-border",
  "--ds-color-border-strong",
  "--ds-color-border-subtle",
  "--ds-color-border-slate-25",
  "--ds-color-border-clay-subtle",
  "--ds-color-border-glass",
  "--ds-color-border-accent",
  "--ds-color-border-inverse-subtle",
  "--ds-color-border-inverse-soft",
  // Colors — overlays & misc
  "--ds-color-overlay",
  "--ds-color-overlay-strong",
  "--ds-color-sheen",
  "--ds-color-white-84",
  "--ds-color-offwhite-85",
  "--ds-color-offwhite-90",
  "--ds-color-gold-35",
  "--ds-color-forest-60",
  "--ds-color-black-12",
  "--ds-color-clay-12",
  "--ds-color-clay-36",
  "--ds-color-forest-700",
  "--ds-color-brevo-placeholder",
  "--ds-color-brevo-link",
  // Colors — print
  "--ds-color-print-bg",
  "--ds-color-print-text",
  "--ds-color-print-link",
  "--ds-color-print-border",
  "--ds-color-print-border-strong",
  // Colors — dark backgrounds
  "--ds-color-bg-code",
  "--ds-color-bg-dark",
  "--ds-color-bg-dark-elevated",
  // Colors — section alt
  "--ds-color-section-alt-base",
  "--ds-color-section-alt-text",
  "--ds-color-section-alt-text-soft",
  "--ds-color-section-alt-link",
  "--ds-color-section-alt-link-hover",
  "--ds-color-section-alt-link-visited",
  "--ds-color-section-alt-accent",
  // Colors — component surfaces
  "--ds-color-hero-overlay",
  "--ds-color-hero-text",
  "--ds-color-stats-bg",
  "--ds-color-footer-bg",
  "--ds-color-footer-text",
  "--ds-color-footer-text-muted",
  "--ds-color-card-bg",
  "--ds-color-card-border",
  "--ds-color-cta",
  "--ds-color-cta-hover",
  "--ds-color-cta-text",
  "--ds-color-surface-alt",
  // Colors — dark page
  "--ds-color-dark-page-text",
  "--ds-color-dark-page-link",
  "--ds-color-dark-page-link-hover",
  "--ds-color-dark-page-link-visited",
  "--ds-color-dark-page-pill-bg",
  // Images / textures
  "--ds-image-section-alt-noise",
  "--ds-image-texture-earth",
  "--ds-image-texture-noise",
  // Gradients
  "--ds-gradient-accent",
  "--ds-gradient-primary",
  "--ds-gradient-vignette-dark",
  // Shadows
  "--ds-shadow-sm",
  "--ds-shadow-md",
  "--ds-shadow-lg",
  "--ds-shadow-xl",
  "--ds-shadow-glass",
  "--ds-shadow-glow",
  "--ds-shadow-header",
  "--ds-shadow-appeal",
  "--ds-shadow-dark-lg",
  "--ds-shadow-text-soft",
  "--ds-shadow-text-dark",
  "--ds-shadow-text-inverse",
  "--ds-shadow-notice-light",
  "--ds-shadow-notice-dark",
  "--ds-shadow-accent",
  "--ds-shadow-accent-hover",
  "--ds-shadow-accent-ui",
  "--ds-shadow-accent-ui-glow",
  "--ds-shadow-accent-ui-hover",
  "--ds-shadow-accent-ui-soft",
  "--ds-shadow-forest-soft",
  "--ds-shadow-forest-strong",
  "--ds-shadow-hero-content",
  "--ds-shadow-hero-features",
  "--ds-shadow-status-indicator",
  "--ds-shadow-services-card-hover",
  "--ds-shadow-input-focus-on-dark",
  "--ds-shadow-price-amount",
  "--ds-shadow-price-compare",
  "--ds-shadow-price-badge",
  "--ds-shadow-qr",
  // Sizing — layout
  "--ds-size-section-padding-x",
  "--ds-size-section-padding-y",
  "--ds-size-1",
  "--ds-size-container-max",
  "--ds-size-section-content-max",
  "--ds-size-container-narrow",
  "--ds-size-container-measure-body",
  "--ds-size-container-measure-heading",
  "--ds-size-header-height",
  "--ds-size-scroll-margin",
  "--ds-size-full",
  "--ds-size-screen-height",
  "--ds-size-process-start-offset",
  // Sizing — icons
  "--ds-size-icon-xl",
  "--ds-size-icon-md",
  "--ds-size-icon-sm",
  "--ds-size-icon-xs",
  "--ds-size-icon-xxs",
  // Sizing — hero
  "--ds-size-hero-mesh-min",
  "--ds-size-hero-mesh-min-sm",
  // Sizing — cards
  "--ds-size-card-inset",
  "--ds-size-card-image",
  // Sizing — bullets
  "--ds-size-bullet-icon",
  "--ds-size-bullet-icon-sm",
  "--ds-size-bullet-lift",
  "--ds-size-bullet-min",
  "--ds-size-bullet-spotlight",
  "--ds-size-bullet-spotlight-stop",
  // Sizing — section numbers
  "--ds-size-section-number-bg",
  "--ds-size-section-number-bg-alt",
  "--ds-size-section-number-bg-layer",
  "--ds-size-section-number-blur",
  "--ds-size-section-number-border",
  "--ds-size-section-number-border-alt",
  "--ds-size-section-number-fluid",
  "--ds-size-section-number-font-fluid",
  "--ds-size-section-number-font-max",
  "--ds-size-section-number-font-min",
  "--ds-size-section-number-layer",
  "--ds-size-section-number-letter",
  "--ds-size-section-number-line",
  "--ds-size-section-number-max",
  "--ds-size-section-number-min",
  "--ds-size-section-number-radius",
  "--ds-size-section-number-shadow",
  "--ds-size-section-number-shadow-alt",
  "--ds-size-section-number-text-layer",
  // Sizing — pricing
  "--ds-size-price-badge",
  "--ds-size-price-badge-icon-offset",
  "--ds-size-price-badge-icon-offset-sm",
  "--ds-size-price-badge-sm",
  "--ds-size-pricing-cards-max",
  "--ds-size-pricing-future-max",
  "--ds-size-pricing-intro-max",
  "--ds-size-pricing-ultimate-max",
  // Sizing — modals/forms
  "--ds-size-modal-max",
  "--ds-size-modal-max-height",
  "--ds-size-modal-accent-top-min",
  "--ds-size-modal-accent-top-max",
  "--ds-size-modal-accent-height-min",
  "--ds-size-modal-accent-height-max",
  "--ds-size-noise-tile",
  "--ds-size-textarea-sm",
  // Sizing — comparison
  "--ds-size-compare-padding",
  "--ds-size-compare-margin",
  "--ds-size-compare-footnote-pad",
  // Sizing — appeal
  "--ds-size-appeal-max",
  "--ds-size-appeal-max-sm",
  "--ds-size-lead-max",
  "--ds-size-option-list-max",
  "--ds-size-notice-max",
  // Sizing — trust
  "--ds-size-trust-icon",
  "--ds-size-trust-icon-sm",
  "--ds-size-industries-card-min",
  // Sizing — channels
  "--ds-size-channel-card-min",
  "--ds-size-channel-card-min-sm",
  "--ds-size-channel-card-min-xs",
  "--ds-size-channel-qr-max",
  "--ds-size-channel-qr-max-sm",
  "--ds-size-channel-qr-max-xs",
  "--ds-size-channel-qr-img-max",
  "--ds-size-channel-qr-img-max-xs",
  // Sizing — services cards
  "--ds-size-services-card-image",
  "--ds-size-services-card-image-sm",
  "--ds-size-services-card-image-xs",
  "--ds-size-services-card-title",
  "--ds-size-services-card-title-sm",
  "--ds-size-services-card-title-xs",
  "--ds-size-services-card-title-letter",
  "--ds-size-services-card-title-line",
  "--ds-size-services-card-desc",
  "--ds-size-services-card-desc-sm",
  "--ds-size-services-card-desc-xs",
  "--ds-size-services-card-desc-line",
  "--ds-size-services-card-desc-line-sm",
  "--ds-size-services-card-bg",
  "--ds-size-services-card-border",
  "--ds-size-services-card-lift",
  // Sizing — funding
  "--ds-size-funding-min",
  "--ds-size-funding-bg-layer",
  "--ds-size-funding-card-max",
  "--ds-size-funding-content-max",
  // Sizing — misc
  "--ds-size-found-us-gap",
  "--ds-size-found-us-gap-lg",
  "--ds-size-found-us-padding",
  "--ds-size-target-card-max",
  "--ds-size-key-icon",
  "--ds-size-key-icon-sm",
  "--ds-size-key-featured-icon",
  "--ds-size-key-featured-icon-sm",
  // Opacity
  "--ds-opacity-muted",
  "--ds-opacity-12",
  "--ds-opacity-60",
  "--ds-opacity-84",
  "--ds-opacity-disabled",
  // Z-index scale (canonical --ds-z-* names)
  "--ds-z-behind",
  "--ds-z-base",
  "--ds-z-content",
  "--ds-z-floating",
  "--ds-z-header",
  "--ds-z-overlay",
  "--ds-z-modal",
  "--ds-z-toast",
] as const;

/** Union type of every design token name defined in tokens.css. */
export type DesignToken = (typeof TOKEN_NAMES)[number];

/** Set of all token names — useful for O(1) membership checks in validators. */
export const TOKEN_NAME_SET: ReadonlySet<string> = new Set(TOKEN_NAMES);

// ---------------------------------------------------------------------------
// Token categories — map each category prefix to the tokens within it
// ---------------------------------------------------------------------------

export const TOKEN_CATEGORIES = {
  rgb: TOKEN_NAMES.filter((t) => t.startsWith("--ds-rgb-")),
  space: TOKEN_NAMES.filter((t) => t.startsWith("--ds-space-")),
  font: TOKEN_NAMES.filter((t) => t.startsWith("--ds-font-")),
  text: TOKEN_NAMES.filter((t) => t.startsWith("--ds-text-")),
  lineHeight: TOKEN_NAMES.filter((t) => t.startsWith("--ds-line-height-")),
  tracking: TOKEN_NAMES.filter((t) => t.startsWith("--ds-tracking-")),
  radius: TOKEN_NAMES.filter((t) => t.startsWith("--ds-radius-")),
  border: TOKEN_NAMES.filter((t) => t.startsWith("--ds-border-")),
  duration: TOKEN_NAMES.filter((t) => t.startsWith("--ds-duration-")),
  ease: TOKEN_NAMES.filter((t) => t.startsWith("--ds-ease-")),
  angle: TOKEN_NAMES.filter((t) => t.startsWith("--ds-angle-")),
  blur: TOKEN_NAMES.filter((t) => t.startsWith("--ds-blur-")),
  filter: TOKEN_NAMES.filter((t) => t.startsWith("--ds-filter-")),
  color: TOKEN_NAMES.filter((t) => t.startsWith("--ds-color-")),
  image: TOKEN_NAMES.filter((t) => t.startsWith("--ds-image-")),
  gradient: TOKEN_NAMES.filter((t) => t.startsWith("--ds-gradient-")),
  shadow: TOKEN_NAMES.filter((t) => t.startsWith("--ds-shadow-")),
  size: TOKEN_NAMES.filter((t) => t.startsWith("--ds-size-")),
  opacity: TOKEN_NAMES.filter((t) => t.startsWith("--ds-opacity-")),
  z: TOKEN_NAMES.filter((t) => t.startsWith("--ds-z-")),
} as const satisfies Record<string, readonly string[]>;
