/*
<MODULE_CONTRACT>
<purpose>RFC-0527 content.ref-index.generate — scans src/content/ for .md and .yaml files, parses
frontmatter (.md) or full content (.yaml), and writes a unified content-ref-index.generated.yaml
index file for the index-based resolver in @warpgogol/share/content-reference.</purpose>
<non-goals>
  <item>Do not resolve references — that is the resolver in @warpgogol/share/content-reference.</item>
  <item>Do not validate references — that is content.references.validate in @warpgogol/site-kernel-checks.</item>
  <item>Do not index markdown body content — only frontmatter is indexed for .md files.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0527: initial implementation of content.ref-index.generate command.</item>
</CHANGE_SUMMARY>
*/

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname, relative, sep } from "node:path";
import { stringify, parse as parseYaml } from "yaml";
import { collectMarkdownFiles, parseMarkdownFrontmatter } from "@warpgogol/site-kernel-content";
import { collectFiles } from "@warpgogol/share/fs";
import type {
  KernelCommandInput,
  KernelCommandResult,
  KernelRuntimeContext,
} from "@warpgogol/site-kernel";
import { requireAstroSitePaths } from "@warpgogol/site-kernel-astro";
import type { ContentRefIndex } from "@warpgogol/share/content-reference";

const INDEX_OUTPUT_PATH = "src/content-ref-index.generated.yaml";
const HEADER_COMMENT =
  "# RFC-0527 content-ref-index — generated by content.ref-index.generate. Do not edit.\n";

export async function runContentRefIndexGenerate(
  _input: KernelCommandInput,
  ctx: KernelRuntimeContext,
): Promise<KernelCommandResult> {
  const command = "content.ref-index.generate";
  const paths = requireAstroSitePaths(ctx);
  const appRoot = paths.appDirectory;
  const contentDir = join(appRoot, "src", "content");
  const outputPath = join(appRoot, INDEX_OUTPUT_PATH);

  const mdFiles = await collectMarkdownFiles(contentDir);
  const yamlFiles = (await collectFiles(contentDir, { extensions: [".yaml", ".yml"] })).filter(
    (f) => !f.endsWith(".credits.yaml") && !f.endsWith(".manifest.yaml"),
  );

  const entries: ContentRefIndex["entries"] = {};
  const collectionSet = new Set<string>();
  let indexed = 0;

  for (const filePath of mdFiles) {
    const relPath = relative(contentDir, filePath).split(sep).join("/");
    const parts = relPath.split("/");

    if (parts.length < 2) continue;

    const collection = parts[0];

    if (collection.startsWith("-") || collection.startsWith("old-")) continue;

    // Language is at parts[1] if it's a 2-letter code; otherwise no language dir.
    const lang = parts.length >= 3 && /^[a-z]{2}$/.test(parts[1]) ? parts[1] : "default";

    // File key = path between collection root and language dir + filename (without extension).
    // For business-profile/de/offerings/digital-foundation.md → offerings/digital-foundation
    const fileParts = lang !== "default" ? parts.slice(2) : parts.slice(1);
    const fileKey = fileParts.join("/").replace(/\.md$/, "");

    let data: Record<string, unknown>;
    try {
      const text = await readFile(filePath, "utf-8");
      const parsed = parseMarkdownFrontmatter(text);
      data = parsed.data as Record<string, unknown>;
    } catch {
      continue;
    }

    if (!entries[collection]) {
      entries[collection] = {};
    }
    if (!entries[collection][fileKey]) {
      entries[collection][fileKey] = {};
    }
    entries[collection][fileKey][lang] = data;
    collectionSet.add(collection);
    indexed++;
  }

  for (const filePath of yamlFiles) {
    const relPath = relative(contentDir, filePath).split(sep).join("/");
    const parts = relPath.split("/");

    if (parts.length < 2) continue;

    const collection = parts[0];

    if (collection.startsWith("-") || collection.startsWith("old-")) continue;

    // Language is at parts[1] if it's a 2-letter code; otherwise no language dir.
    const lang = parts.length >= 3 && /^[a-z]{2}$/.test(parts[1]) ? parts[1] : "default";

    const fileParts = lang !== "default" ? parts.slice(2) : parts.slice(1);
    const fileKey = fileParts.join("/").replace(/\.(ya?ml)$/, "");

    let data: Record<string, unknown>;
    try {
      const text = await readFile(filePath, "utf-8");
      data = parseYaml(text) as Record<string, unknown>;
    } catch {
      continue;
    }

    if (!data || typeof data !== "object") continue;

    if (!entries[collection]) {
      entries[collection] = {};
    }
    if (!entries[collection][fileKey]) {
      entries[collection][fileKey] = {};
    }
    entries[collection][fileKey][lang] = data;
    collectionSet.add(collection);
    indexed++;
  }

  const index: ContentRefIndex = {
    version: 1,
    generatedAt: null,
    entries,
    collections: [...collectionSet].sort(),
  };

  const yamlContent = HEADER_COMMENT + stringify(index);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, yamlContent, "utf-8");

  return {
    data: {
      command,
      status: "pass",
      indexed,
      collections: index.collections.length,
      outputPath: INDEX_OUTPUT_PATH,
    },
    exitCode: 0,
    summary: `${command}: OK — ${indexed} entries across ${index.collections.length} collections`,
  };
}
