// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: 3ee00eeb5169e32c585d140ca0574c210c0d7f37c113913313f5e27c90f62364
// Source: packages/ui/src/sections/problem/problem-section.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface ProblemSectionContent {
  background?: {
    kind: "color";
    color?: string;
  } | {
    kind: "image";
    imageName: string;
    fit?: "cover" | "tile" | "stretch-width" | "stretch-height";
    quality?: "low" | "mid" | "high" | "max";
    tintOpacity?: number;
  } | {
    kind: "texture";
    texture: string;
  } | {
    kind: "transparent";
  } | {
    kind: "fade";
    direction: "vertical" | "horizontal";
    from?: string;
    to?: string;
    startOpacity?: number;
    endOpacity?: number;
    inset?: number;
    noStartFade?: boolean;
    noEndFade?: boolean;
  };
  effects?: ({
    target: string;
    stack: ({
      kind: "glass";
      enabled: boolean;
      blur?: number;
      saturate?: number;
      tint?: string;
      tintOpacity?: number;
      border?: "hairline" | "none";
    } | {
      kind: "shadow";
      enabled: boolean;
      offsetX?: number;
      offsetY?: number;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "glow";
      enabled: boolean;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "bulge";
      enabled: boolean;
      depth?: number;
      highlight?: number;
      shade?: number;
    } | {
      kind: "tilt";
      enabled: boolean;
      rotate?: number;
      skewX?: number;
    })[];
  })[];
  density?: "compact" | "normal" | "spacious";
  tone?: "default" | "warning" | "success" | "muted";
  containerVariant?: "default" | "narrow" | "full";
  motion?: {
    reveal?: {
      variant?: "fade" | "fade-up" | "fade-up-stagger";
      once?: boolean;
      threshold?: number;
    };
    parallax?: {
      variant?: "subtle" | "balanced" | "dramatic";
      speed?: number;
    };
    stagger?: {
      delay?: number;
      childSelector?: string;
    };
    off?: boolean;
  };
  header: {
    heading: string | ({
      text: string;
      tone?: "default" | "primary" | "accent" | "muted" | "inverse";
    })[];
    subheading?: string;
    align?: "left" | "center" | "right";
    level?: 1 | 2;
    hideSectionNumber?: boolean;
  };
  body: {
    kind: "paragraphs";
    paragraphs: string[];
    align?: "left" | "center" | "right";
  };
}
