// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: f0473b241d92940f17b80c2344c77048612aa68c54bdc1276769403caed1c736
// Source: packages/ui/src/components/not-found/not-found-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface NotFoundComponentContent {
  lang: string;
  title: string;
  intro: string;
  homeLabel: string;
  homeHref: string;
  primaryLabel?: string;
  primaryHref?: string;
  contactLabel?: string;
  contactHref?: string;
}
