// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: 56c550ce966dcda7e4b78dad71be39276016a076119a7f2aa947f3b5709d84d2
// Source: packages/werkstatt-site/src/domain/ui/components/scroll-to-top/scroll-to-top-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface ScrollToTopComponentContent {
  ariaLabel?: string;
}
