// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: 1a328a5140c04cd537f611c39fd20de0deeba4270412e50c1ca1e51302aa4c4f
// Source: packages/ui/src/sections/hero/hero-section.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface HeroSectionContent {
  background?: {
    kind: "color";
    color?: string;
  } | {
    kind: "image";
    imageName: string;
    fit?: "cover" | "tile" | "stretch-width" | "stretch-height";
    quality?: "low" | "mid" | "high" | "max";
    tintOpacity?: number;
  } | {
    kind: "texture";
    texture: string;
  } | {
    kind: "transparent";
  } | {
    kind: "fade";
    direction: "vertical" | "horizontal";
    from?: string;
    to?: string;
    startOpacity?: number;
    endOpacity?: number;
    inset?: number;
    noStartFade?: boolean;
    noEndFade?: boolean;
  };
  effects?: ({
    target: string;
    stack: ({
      kind: "glass";
      enabled: boolean;
      blur?: number;
      saturate?: number;
      tint?: string;
      tintOpacity?: number;
      border?: "hairline" | "none";
    } | {
      kind: "shadow";
      enabled: boolean;
      offsetX?: number;
      offsetY?: number;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "glow";
      enabled: boolean;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "bulge";
      enabled: boolean;
      depth?: number;
      highlight?: number;
      shade?: number;
    } | {
      kind: "tilt";
      enabled: boolean;
      rotate?: number;
      skewX?: number;
    })[];
  })[];
  density?: "compact" | "normal" | "spacious";
  tone?: "default" | "warning" | "success" | "muted";
  containerVariant?: "default" | "narrow" | "full";
  motion?: {
    reveal?: {
      variant?: "fade" | "fade-up" | "fade-up-stagger";
      once?: boolean;
      threshold?: number;
    };
    parallax?: {
      variant?: "subtle" | "balanced" | "dramatic";
      speed?: number;
    };
    stagger?: {
      delay?: number;
      childSelector?: string;
    };
    off?: boolean;
  };
  header: {
    heading: string | ({
      text: string;
      tone?: "default" | "primary" | "accent" | "muted" | "inverse";
    })[];
    eyebrow?: string;
    subheading?: string;
    align?: "left" | "center" | "right";
    level?: 1 | 2;
    hideSectionNumber?: boolean;
  };
  hideSectionNumber?: boolean;
  tagline?: string;
  subheading?: string;
  description?: string;
  imageAlt?: string;
  backgroundImage?: string;
  portraitImage?: string;
  leadImage?: {
    src: string;
    alt: string;
  };
  leadImageFade?: {
    top?: boolean;
    bottom?: boolean;
    left?: boolean;
    right?: boolean;
    width?: number;
  };
  leadImagePlacement?: "portrait" | "after-heading";
  ctaPrimaryLabel?: string;
  ctaPrimaryAriaLabel?: string;
  ctaSecondaryLabel?: string;
  ctaSecondaryAriaLabel?: string;
  ctaSecondaryUrl?: string;
  ctaPrimaryUrl?: string;
  primaryCtaTarget?: string;
  secondaryCtaTarget?: string;
  animated?: boolean;
  creditDisplay?: "shown" | "hidden";
  stats?: {
    value?: string;
    label: string;
    numericValue?: number;
    prefix?: string;
    suffix?: string;
    decimals?: number;
    duration?: number;
  }[];
}
