// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: f7d92bd7cd1b9e4ab062875b1f685bb77784941b6748190bbe1f49ce0b7b54c8
// Source: packages/ui/src/components/donation-card/donation-card-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface DonationCardComponentContent {
  lang?: string;
  content: {
    title: string;
    ibanLabel: string;
    bicLabel: string;
    bankLabel: string;
    copyButtonLabel: string;
    qrCodeButtonLabel: string;
    donationInfoLinkLabel: string;
    oldDetailsLabel: string;
    oldDetailsButtonLabel: string;
    oldDetailsButtonExpandedLabel: string;
    kontoLabel: string;
    blzLabel: string;
    qrCodeModalTitle: string;
    qrCodeModalCloseLabel: string;
    qrCodeAltText: string;
    qrInstruction: string;
    donationInfoLinkHref: string;
    modalCloseIcon: string;
  };
  companyName: string;
  bankName: string;
  iban: string;
  bic: string;
  konto?: string;
  blz?: string;
  trustIndicators?: string[];
}
