// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: 782976dbbeaff1654b1c266637ae65fcc002717175bb23b0e12f87cdd77e32f2
// Source: packages/ui/src/sections/breadcrumbs/breadcrumbs-section.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface BreadcrumbsSectionContent {
  hideSectionNumber?: boolean;
  items?: {
    name: string;
    url: string;
  }[];
}
