/*
<MODULE_CONTRACT>
<purpose>
  Codegen script: reads ontology growth event YAML files and generates
  event-names.generated.ts with the EVENT_NAMES array. Run via
  `pnpm --filter @warpgogol/growth run codegen:event-names`.
</purpose>
<non-goals>
  <item>Do not run at import time — this is a build-time codegen step.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Architecture review 2026-07-14: generate EVENT_NAMES from ontology YAML files instead of hand-maintaining the array.</item>
</CHANGE_SUMMARY>
*/

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const EVENTS_DIR = join(__dirname, "..", "..", "ontology", "growth", "events");
const OUTPUT_FILE = join(__dirname, "..", "src", "event-names.generated.ts");

async function main() {
  const files = await readdir(EVENTS_DIR);
  const yamlFiles = files.filter((f) => f.endsWith(".yaml")).sort();

  const eventIds: string[] = [];
  for (const file of yamlFiles) {
    const content = await readFile(join(EVENTS_DIR, file), "utf8");
    const parsed = parseYaml(content) as { id?: string };
    if (typeof parsed.id === "string" && parsed.id.length > 0) {
      eventIds.push(parsed.id);
    }
  }

  eventIds.sort();

  const lines = eventIds.map((id) => `  "${id}",`).join("\n");

  const output = `/*
 * GENERATED CODE — DO NOT EDIT.
 * Generated by scripts/gen-event-names.ts from packages/ontology/growth/events/*.yaml
 * Run \`pnpm --filter @warpgogol/growth run codegen:event-names\` to regenerate.
 */
export const EVENT_NAMES = [
${lines}
] as const;

export type EventName = (typeof EVENT_NAMES)[number];
`;

  await writeFile(OUTPUT_FILE, output, "utf8");
  console.log(`Generated ${eventIds.length} event names → ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
