// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: 44fbda93285ae2951073d25e1363872ca650afa3a40f67b0c8a33070b8054b4b
// Source: packages/werkstatt-site/src/domain/ui/components/footer-promo/footer-promo-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface FooterPromoComponentContent {
  text: string;
  cards: {
    title: string;
    image?: string;
    imageAlt: string;
  }[];
}
