// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec site-kernel run props.types.generate
// sourceHash: f53fefa0511c4ad677441d8382f72592044b1a0f78d3ef87b07e5dd0dca38ffe
// Source: packages/ui/src/components/footer/footer-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface FooterComponentContent {
  texture?: boolean;
  lang?: string;
  defaultLang?: string;
  pageOverride?: {
    portraitAlt?: string;
    logoFirstSegment?: string;
    logoSecondSegment?: string;
    qrAlt?: string;
    taglineLines?: string[];
    motto?: string;
    pulseUrl?: string;
    texture?: boolean;
    backgroundImage?: string;
    navAriaLabel?: string;
    navGroups?: {
      navigationTitle?: string;
      legalTitle?: string;
      contactTitle?: string;
      transparencyTitle?: string;
    };
    navigationLinks?: ({
      label: string;
      href?: string;
      external?: boolean;
      featureFlag?: string;
      semanticTarget?: {
        kind: "internal" | "external";
        pageId?: string;
        anchor?: string;
        href?: string;
      };
    })[];
    legalLinks?: ({
      label: string;
      href?: string;
      external?: boolean;
      featureFlag?: string;
      semanticTarget?: {
        kind: "internal" | "external";
        pageId?: string;
        anchor?: string;
        href?: string;
      };
    })[];
    transparencyIds?: string[];
    transparencyLinks?: ({
      label: string;
      href?: string;
      external?: boolean;
      featureFlag?: string;
      semanticTarget?: {
        kind: "internal" | "external";
        pageId?: string;
        anchor?: string;
        href?: string;
      };
    })[];
    whatsappLabel?: string;
    whatsappHref?: string;
    telegramLabel?: string;
    telegramHref?: string;
    disabledContactHref?: string;
    copyEmailAriaLabel?: string;
    copyEmailTitle?: string;
    contact?: {
      email?: string;
      city?: {
        name: string;
        postalCode?: string;
        url?: string;
      };
      region?: {
        name: string;
        url?: string;
      };
      country?: {
        name: string;
        url?: string;
      };
    };
    contactIds?: string[];
    copyrightSuffix?: string;
    photo?: {
      position: "before" | "behind";
      src: string;
      alt: string;
    };
    statusLinkTitleSuffix?: string;
    statusLinkAriaLabelSuffix?: string;
    statusIconAriaLabel?: string;
  };
}
