// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: bc0f848a17f19901a5c64e911ccea65f9f45d78cc7c9a5d0963ecb075ac0ff59
// Source: packages/ui/src/components/site-background/site-background-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface SiteBackgroundComponentContent {
  layers: unknown[];
  lang?: string;
}
