// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec site-kernel run props.types.generate
// sourceHash: 6e6efbb8e6c7f326bee94765f7c1195caea9213c08ce2eda1cc679b6bd71d63d
// Source: packages/ui/src/components/header/header-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface HeaderComponentContent {
  texture?: boolean;
  navAriaLabel: string;
  mobileNavAriaLabel: string;
  menuButtonAriaLabel: string;
  overflowMenuLabel: string;
  overflowMenuAriaLabel: string;
  ctaLabel: string;
  motto?: string;
  navLinks: ({
    label: string;
    target?: string;
    semanticTarget?: {
      kind: "internal" | "external";
      pageId?: string;
      anchor?: string;
      href?: string;
    };
  })[];
}
