/*
<MODULE_CONTRACT>
<purpose>Canonical GENERATED_MARKER constant and advisory header builder for
generated-file governance. Moved from @warpgogol/site-kernel to forge as canonical
source (dependency inversion).</purpose>
<non-goals>
  <item>Do not perform file I/O — operates on in-memory content strings only.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Moved from @warpgogol/site-kernel/generated-marker to forge as canonical source.</item>
  <item>Added optional commandPrefix to GeneratedHeaderInput — defaults to "forge" for autonomous mode; site-kernel passes "pnpm exec werkstatt run".</item>
</CHANGE_SUMMARY>
*/

export const GENERATED_MARKER =
  "GENERATED. Do not change this line unless the file contains project specific changes.";

export function hasGeneratedMarker(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

export interface StripGeneratedMarkerResult {
  changed: boolean;
  content: string;
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const DO_NOT_EDIT_LINE = "DO NOT EDIT THIS FILE. Changes are overwritten on the next build.";

export function stripGeneratedMarker(content: string): StripGeneratedMarkerResult {
  const raw = GENERATED_MARKER;
  let result = content;
  let changed = false;

  const applyAll = (patterns: RegExp[]): void => {
    for (const pattern of patterns) {
      const next = result.replace(pattern, "");
      if (next !== result) {
        changed = true;
        result = next;
      }
    }
  };

  applyAll([
    new RegExp(`<!--[ \\t]*\\n[\\s\\S]*?${escapeRegex(raw)}[\\s\\S]*?-->\\n?`, "g"),
    new RegExp(`/\\*[ \\t]*\\n[\\s\\S]*?${escapeRegex(raw)}[\\s\\S]*?\\*/\\n?`, "g"),
  ]);

  for (const token of ["//", "#"]) {
    const t = escapeRegex(token);
    const advisoryLine = (suffix: string): string => `(?:[ \\t]*${t}[ \\t]*${suffix}\\n)?`;
    const pattern = new RegExp(
      `^[ \\t]*${t}[ \\t]*${escapeRegex(raw)}\\n` +
        advisoryLine(escapeRegex(DO_NOT_EDIT_LINE)) +
        advisoryLine("Owner command:.*") +
        advisoryLine("Edit instead:.*") +
        advisoryLine("Regenerate:.*"),
      "gm",
    );
    applyAll([pattern]);
  }

  applyAll([
    new RegExp(`^\\s*<!--\\s*${escapeRegex(raw)}\\s*-->\\n?`, "gm"),
    new RegExp(`^\\s*//\\s*${escapeRegex(raw)}\\n?`, "gm"),
    new RegExp(`^\\s*/\\*\\s*${escapeRegex(raw)}\\s*\\*/\\n?`, "gm"),
    new RegExp(`^\\s*#\\s*${escapeRegex(raw)}\\n?`, "gm"),
    new RegExp(`^\\s*${escapeRegex(raw)}\\n?`, "gm"),
  ]);

  if (result.includes(raw)) {
    const next = result.split(raw).join("");
    if (next !== result) {
      changed = true;
      result = next;
    }
  }

  return { changed, content: result };
}

export interface GeneratedHeaderInput {
  filePath: string;
  ownerCommand: string;
  templatePath?: string;
  site?: string;
  /**
   * Command prefix for the regenerate hint. Defaults to "forge" (autonomous mode).
   * Site-kernel callers pass "pnpm exec werkstatt run" for Warpgogol context.
   */
  commandPrefix?: string;
}

type GeneratedHeaderCommentStyle = "line-slash" | "line-hash" | "block-html" | "block-css";

function commentStyleForPath(filePath: string): GeneratedHeaderCommentStyle {
  const lower = filePath.toLowerCase().replace(/\\/g, "/");
  const base = lower.slice(lower.lastIndexOf("/") + 1);
  if (
    base === ".gitattributes" ||
    base === "_headers" ||
    base === "_redirects" ||
    base.endsWith(".txt") ||
    base.endsWith(".yml") ||
    base.endsWith(".yaml")
  ) {
    return "line-hash";
  }
  if (base.endsWith(".md")) return "block-html";
  if (base.endsWith(".css")) return "block-css";
  return "line-slash";
}

export function buildGeneratedHeader(input: GeneratedHeaderInput): string {
  const style = commentStyleForPath(input.filePath);
  const prefix = input.commandPrefix ?? "forge";
  const regenerateCommand = input.site
    ? `${prefix} ${input.ownerCommand} --site ${input.site}`
    : `${prefix} ${input.ownerCommand}`;
  const editInstead = input.templatePath
    ? `Edit instead: ${input.templatePath}`
    : `Edit instead: the ${input.ownerCommand} generator source (not this file).`;

  const lines = [
    GENERATED_MARKER,
    DO_NOT_EDIT_LINE,
    `Owner command: ${input.ownerCommand}`,
    editInstead,
    `Regenerate:   ${regenerateCommand}`,
  ];

  switch (style) {
    case "line-slash":
      return `${lines.map((line) => `// ${line}`).join("\n")}\n`;
    case "line-hash":
      return `${lines.map((line) => `# ${line}`).join("\n")}\n`;
    case "block-css":
      return `/*\n${lines.map((line) => `  ${line}`).join("\n")}\n*/\n`;
    case "block-html":
      return `<!--\n${lines.map((line) => `  ${line}`).join("\n")}\n-->\n`;
  }
}

export function isGeneratedMarkerTextCandidate(filePath: string): boolean {
  const ext = filePath.slice(filePath.lastIndexOf(".")).toLowerCase();
  const TEXT_EXTS = new Set([
    ".txt",
    ".xml",
    ".md",
    ".yml",
    ".yaml",
    ".css",
    ".js",
    ".mjs",
    ".ts",
    ".json",
    ".html",
    ".astro",
  ]);
  return TEXT_EXTS.has(ext);
}
