// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: b59e139d5486a49e1c460cd9f8b9bde4fdb9f3e140f46be9445d95f0ed9efce4
// Source: packages/ui/src/sections/send-message/send-message-section.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface SendMessageSectionContent {
  background?: {
    kind: "color";
    color?: string;
  } | {
    kind: "image";
    imageName: string;
    fit?: "cover" | "tile" | "stretch-width" | "stretch-height";
    quality?: "low" | "mid" | "high" | "max";
    tintOpacity?: number;
  } | {
    kind: "texture";
    texture: string;
  } | {
    kind: "transparent";
  } | {
    kind: "fade";
    direction: "vertical" | "horizontal";
    from?: string;
    to?: string;
    startOpacity?: number;
    endOpacity?: number;
    inset?: number;
    noStartFade?: boolean;
    noEndFade?: boolean;
  };
  effects?: ({
    target: string;
    stack: ({
      kind: "glass";
      enabled: boolean;
      blur?: number;
      saturate?: number;
      tint?: string;
      tintOpacity?: number;
      border?: "hairline" | "none";
    } | {
      kind: "shadow";
      enabled: boolean;
      offsetX?: number;
      offsetY?: number;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "glow";
      enabled: boolean;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "bulge";
      enabled: boolean;
      depth?: number;
      highlight?: number;
      shade?: number;
    } | {
      kind: "tilt";
      enabled: boolean;
      rotate?: number;
      skewX?: number;
    })[];
  })[];
  density?: "compact" | "normal" | "spacious";
  tone?: "default" | "warning" | "success" | "muted";
  containerVariant?: "default" | "narrow" | "full";
  motion?: {
    reveal?: {
      variant?: "fade" | "fade-up" | "fade-up-stagger";
      once?: boolean;
      threshold?: number;
    };
    parallax?: {
      variant?: "subtle" | "balanced" | "dramatic";
      speed?: number;
    };
    stagger?: {
      delay?: number;
      childSelector?: string;
    };
    off?: boolean;
  };
  header: Record<string, never>;
  body?: {
    paragraphs: string[];
    align?: "left" | "center" | "right";
  };
  formId?: string;
  endpoint?: string;
  placeholder: string;
  buttonLabel: string;
  sendingLabel?: string;
  successMessage: string;
  errorMessage: string;
  emptyMessage?: string;
  minMessageLength?: number;
  fallbackEmail?: string;
  fallbackEmailLabel?: string;
  fallbackBodyLabel?: string;
  copyMessageLabel?: string;
  contactRequirementMessage?: string;
  checklistTitle?: string;
  checklistReadyLabel?: string;
  checklistLengthLabel?: string;
  checklistContactLabel?: string;
  checklistItems?: ({
    id: string;
    label: string;
    rule: "min-length" | "contact-details" | "url-presence" | "keyword-match";
    value?: number;
    keywords?: string[];
  })[];
  referrerField?: {
    enabled: boolean;
    required: boolean;
    label?: string;
    placeholder?: string;
  };
}
