/*
<MODULE_CONTRACT>
<purpose>Nested AGENTS.md template builder (RFC-0611). Pure function that renders
minimal stub content for a workspace AGENTS.md using the existing generated marker
infrastructure. No I/O.</purpose>
<non-goals>
  <item>Do not read or write files — this is a pure render function.</item>
  <item>Do not add type-specific sections beyond the minimal stub — content evolves in code.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0611: initial minimal stub template for app, package, service workspaces.</item>
</CHANGE_SUMMARY>
*/

import { buildGeneratedHeader } from "../utils/index.ts";
import type { ForgeConfig } from "../config/forge-config.ts";
import type { WorkspaceDir, WorkspaceType } from "./workspace-discovery.ts";

const TYPE_GUIDANCE: Record<WorkspaceType, string> = {
  app: "This is an app workspace. Follow thin-route and content-driven composition rules from the root AGENTS.md.",
  package:
    "This is a package workspace. Expose stable typed APIs. Do not import from apps or services.",
  service:
    "This is a service workspace. Runtime composition only. Shared schemas and validators belong in packages.",
};

const TYPE_LABEL: Record<WorkspaceType, string> = {
  app: "App",
  package: "Package",
  service: "Service",
};

export function buildNestedAgentsMd(
  workspace: WorkspaceDir,
  _config: ForgeConfig,
): string {
  const header = buildGeneratedHeader({
    filePath: "AGENTS.md",
    ownerCommand: "forge.agents.generate",
    commandPrefix: "forge",
  });

  const lines: string[] = [];
  lines.push(header);
  lines.push("");
  lines.push(`# Agent Guide: ${workspace.path}`);
  lines.push("");
  lines.push(`> This file is generated by \`forge.agents.generate\` (RFC-0611).`);
  lines.push(`> Do not edit by hand — re-run \`forge agents generate\` to regenerate.`);
  lines.push("");
  lines.push(`**Workspace type:** ${TYPE_LABEL[workspace.type]}`);
  lines.push("");
  lines.push(TYPE_GUIDANCE[workspace.type]);
  lines.push("");
  lines.push("See the root `AGENTS.md` for project-wide rules, skills, and capabilities.");
  lines.push("");

  return lines.join("\n");
}
