// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec site-kernel run props.types.generate
// sourceHash: c25cfa4afa0c0d557a001d00d97d560478b9d3deee92172dec704e952b409257
// Source: packages/ui/src/sections/price-card/price-card-section.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface PriceCardSectionContent {
  background?: {
    kind: "color";
    color?: string;
  } | {
    kind: "image";
    imageName: string;
    fit?: "cover" | "tile" | "stretch-width" | "stretch-height";
    quality?: "low" | "mid" | "high" | "max";
    tintOpacity?: number;
  } | {
    kind: "texture";
    texture: string;
  } | {
    kind: "transparent";
  } | {
    kind: "fade";
    direction: "vertical" | "horizontal";
    from?: string;
    to?: string;
    startOpacity?: number;
    endOpacity?: number;
    inset?: number;
    noStartFade?: boolean;
    noEndFade?: boolean;
  };
  effects?: ({
    target: string;
    stack: ({
      kind: "glass";
      enabled: boolean;
      blur?: number;
      saturate?: number;
      tint?: string;
      tintOpacity?: number;
      border?: "hairline" | "none";
    } | {
      kind: "shadow";
      enabled: boolean;
      offsetX?: number;
      offsetY?: number;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "glow";
      enabled: boolean;
      blur?: number;
      color?: string;
      opacity?: number;
    } | {
      kind: "bulge";
      enabled: boolean;
      depth?: number;
      highlight?: number;
      shade?: number;
    } | {
      kind: "tilt";
      enabled: boolean;
      rotate?: number;
      skewX?: number;
    })[];
  })[];
  density?: "compact" | "normal" | "spacious";
  tone?: "default" | "warning" | "success" | "muted";
  containerVariant?: "default" | "narrow" | "full";
  motion?: {
    reveal?: {
      variant?: "fade" | "fade-up" | "fade-up-stagger";
      once?: boolean;
      threshold?: number;
    };
    parallax?: {
      variant?: "subtle" | "balanced" | "dramatic";
      speed?: number;
    };
    stagger?: {
      delay?: number;
      childSelector?: string;
    };
    off?: boolean;
  };
  header: {
    heading: string | ({
      text: string;
      tone?: "default" | "primary" | "accent" | "muted" | "inverse";
    })[];
    eyebrow?: string;
    subheading?: string;
    align?: "left" | "center" | "right";
    level?: 1 | 2;
    hideSectionNumber?: boolean;
  };
  monthly?: {
    amount?: string;
    currency?: string;
    recurrence?: string;
  };
  yearly?: {
    amount?: string;
    currency?: string;
    recurrence?: string;
  };
  setup?: {
    amount?: string;
    currency?: string;
    recurrence?: string;
  };
  includes?: {
    text: string;
    icon?: {
      vendor: string;
      collection: string;
      name: string;
      size?: number;
    };
  }[];
}
