{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>Centralizes the definition of content collections for structured data access in the application.</purpose>
<non-goals>
  <item>Do not source content from src/data/**.</item>
  <item>Do not manage transport or configuration logic.</item>
  <item>Do not include unrelated business logic.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Autogenerated file.</item>
</CHANGE_SUMMARY>
*/

// [DNA-04][DNA-10] Content collections are the ONLY source of typed, validated content.
// Register all collections here. Export their types for page routes to use.
//
// Rules:
// - Collections for component copy: use markdownCollectionLoader
// - Collections for page shell: use markdownCollectionLoader
// - Collections for entity data (pSEO): use markdownCollectionLoader
// - Never source content from src/data/** (removed architecture)

import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";
import { markdownCollectionLoader } from "@warpgogol/share/astro/loaders";
import { fsDataCollectionLoader } from "@warpgogol/content-source";
import { pbpCollections } from "@warpgogol/pbp/astro";
import { createFaqCollection } from "@warpgogol/faq/astro";
import { toDataEntryId } from "@warpgogol/share/content";

const system = defineCollection({
  loader: glob({
    pattern: "system.md",
    base: "src/content",
    generateId: () => "system",
  }),
  schema: z.object({}).loose(),
});

// Loads all .md files from src/content/pages/ as the "pages" collection.
const pages = defineCollection({
  loader: markdownCollectionLoader("src/content/pages"),
  schema: z.object({}).loose(),
});

const prose = defineCollection({
  loader: markdownCollectionLoader("src/content/prose"),
  schema: z.object({}).loose(),
});

const site = defineCollection({
  loader: markdownCollectionLoader("src/content/site"),
  schema: z.object({}).loose(),
});

// Loads navigation.md files from src/content/navigation/{lang}/ as the "navigation" collection (RFC-0044).
// Contains content-declared navigation target definitions for client-editable navigation structure.
// Runtime validation in navigation.ts ensures data structure correctness.
const navigation = defineCollection({
  loader: markdownCollectionLoader("src/content/navigation"),
  schema: z.object({}).loose(),
});

// Loads person records from src/content/people/{lang}/ as the "people" collection (RFC-0200).
// Used by the data-driven People section (@warpgogol/share/astro/people.ts).
const people = defineCollection({
  loader: fsDataCollectionLoader({
    base: "src/content/people",
    generateId: (entry) => toDataEntryId(entry),
  }),
  schema: z.object({}).catchall(z.any()),
});

const faq = createFaqCollection();

export const collections = {
  ...pbpCollections,
  system,
  pages,
  prose,
  site,
  navigation,
  people,
  ...faq,
  // Future collections (pSEO entities) are added here:
  // industries,
  // cities,
  // topics,
};

// Page-data and component-content types are exported from @warpgogol/ui and
// @warpgogol/share. Apps must not re-declare them here.
