{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>Root middleware entry point that chains all Astro request middleware.</purpose>
<non-goals>
  <item>Do not implement middleware logic here — delegate to sub-modules.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Autogenerated file.</item>
</CHANGE_SUMMARY>
*/
// @ai-invariant: High-risk module. Middleware chain. Language redirect runs first.
import languageRedirectMiddleware from "./middleware/language-redirect";

export const onRequest = languageRedirectMiddleware;
