{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>Root middleware entry point that chains all Astro request middleware.</purpose>
<non-goals>
  <item>Do not implement middleware logic here — delegate to sub-modules.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Autogenerated file.</item>
  <item>RFC-0569: chain dev-normalize middleware in dev mode for egress parity.</item>
</CHANGE_SUMMARY>
*/
// @ai-invariant: High-risk module. Middleware chain. Language redirect runs first.
// RFC-0569: dev-normalize middleware applies egress text normalization in dev mode.
import languageRedirectMiddleware from "./middleware/language-redirect";
import { createDevNormalizeMiddleware, resolveNormalizeConfig } from "@warpgogol/share/text-normalize";
import { loadSystemManifestSync } from "@warpgogol/site-kernel-content";

const devNormalize = createDevNormalizeMiddleware(
  resolveNormalizeConfig(loadSystemManifestSync("src/content").manifest),
);

export const onRequest = import.meta.env.DEV
  ? [languageRedirectMiddleware, devNormalize]
  : languageRedirectMiddleware;
