// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: cf0fb61d78dd26487ec143002517b378c791d2bb97176d4c7713ef16be976a90
// Source: packages/ui/src/components/currency-aware-price-display/currency-aware-price-display-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface CurrencyAwarePriceDisplayComponentContent {
  priceVariants: {
    currency: string;
    formatted: string;
    note?: unknown;
  }[];
}
