// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: 14cc531961d06e3626b735b4e7c49cf710faecfbb6f8d3240e3e5ecf15981d20
// Source: packages/werkstatt-site/src/domain/ui/components/brand-label/brand-label-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface BrandLabelComponentContent {
  brandLabel: string;
  brandAriaLabel: string;
  brandImage?: string;
}
