import { describe, it, expect } from "vitest";
import { mkdtemp, writeFile, mkdir, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runRedirectShadowValidate } from "../redirect-shadow.ts";
import type { KernelRuntimeContext } from "@warpgogol/werkstatt/kernel";

/*
<MODULE_CONTRACT>
<purpose>
  Verify RFC-0905: redirect.shadow.validate detects static file shadows (RSHAD-01),
  Worker route shadows (RSHAD-02), and stale target files (RSHAD-03).
</purpose>
<non-goals>
  <item>Do not test redirect.map.validate — that is tested in redirect-map-validate.test.ts.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0905: initial test suite for redirect.shadow.validate.</item>
</CHANGE_SUMMARY>
*/

async function makeContext(root: string, appDir?: string): Promise<KernelRuntimeContext> {
  return {
    workspaceRoot: root,
    site: {
      name: "test-app",
      directory: appDir ?? join(root, "test-app"),
      toolsDirectory: join(root, "tools"),
    },
    io: {
      readFile: async (p: string) => {
        const { readFile: fsReadFile } = await import("node:fs/promises");
        return fsReadFile(p, "utf8");
      },
      glob: async (pattern: string, opts?: { cwd?: string }) => {
        const { readdir } = await import("node:fs/promises");
        const { relative } = await import("node:path");
        const cwd = opts?.cwd ?? root;
        const patternRegex = new RegExp(pattern.replace(/\./g, "\\.").replace(/\*/g, ".*"));
        const results: string[] = [];
        async function scan(dir: string) {
          const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
          for (const entry of entries) {
            const fullPath = join(dir, entry.name);
            if (entry.isDirectory()) {
              await scan(fullPath);
            } else {
              const rel = relative(cwd, fullPath);
              if (patternRegex.test(rel) || patternRegex.test(entry.name)) {
                results.push(rel);
              }
            }
          }
        }
        await scan(cwd);
        return results;
      },
      exists: async (p: string) => {
        const { access } = await import("node:fs/promises");
        try {
          await access(p);
          return true;
        } catch {
          return false;
        }
      },
    },
    dryRun: false,
  } as unknown as KernelRuntimeContext;
}

async function setupApp(
  root: string,
  opts: {
    redirects?: string;
    distClientFiles?: Array<{ path: string; content?: string }>;
    wranglerJsonc?: string;
    registryYaml?: string;
    sitemapXml?: string;
  },
): Promise<string> {
  const appDir = join(root, "test-app");
  const publicDir = join(appDir, "public");
  const distClientDir = join(appDir, "dist", "client");
  const contentDir = join(appDir, "src", "content");

  await mkdir(contentDir, { recursive: true });
  await mkdir(publicDir, { recursive: true });
  await mkdir(distClientDir, { recursive: true });

  await writeFile(
    join(contentDir, "system.md"),
    [
      "---",
      "app: test-app",
      "identity:",
      "  domain: example.com",
      "i18n:",
      "  default: de",
      "  supported:",
      "    de:",
      "      name: Deutsch",
      "      hreflang: de",
      "---",
      "",
      "# Test App",
    ].join("\n"),
  );

  if (opts.redirects !== undefined) {
    await writeFile(join(publicDir, "_redirects"), opts.redirects);
  }

  for (const file of opts.distClientFiles ?? []) {
    const filePath = join(distClientDir, file.path);
    const dir = join(filePath, "..");
    await mkdir(dir, { recursive: true });
    await writeFile(filePath, file.content ?? "<html></html>");
  }

  if (opts.wranglerJsonc !== undefined) {
    await writeFile(join(appDir, "wrangler.jsonc"), opts.wranglerJsonc);
  }

  const systemsDir = join(root, "systems");
  await mkdir(systemsDir, { recursive: true });
  await writeFile(
    join(systemsDir, "registry.yaml"),
    opts.registryYaml ??
      "schemaVersion: 1.0.0\nsystems:\n  - id: test-app\n    deployment:\n      adapter: cloudflare-workers\n",
  );

  if (opts.sitemapXml !== undefined) {
    await writeFile(join(publicDir, "sitemap.xml"), opts.sitemapXml);
  }

  return appDir;
}

const GENERATED_MARKER = "<!-- GENERATED by public.infrastructure.generate -->\n";

describe("redirect.shadow.validate (RFC-0905)", () => {
  it("RSHAD-01: static file at redirect source → error", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /new-page/ 301\n`,
        distClientFiles: [{ path: "old-page/index.html" }],
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      expect(result.data!.status).toBe("fail");
      const rshad01 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-01");
      expect(rshad01).toBeDefined();
      expect(rshad01?.severity).toBe("error");
      expect(rshad01?.message).toContain("/old-page");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-01: no static file → no error", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /new-page/ 301\n`,
        distClientFiles: [],
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad01 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-01");
      expect(rshad01).toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-01: pattern sources are skipped", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old/* /new/ 301\n`,
        distClientFiles: [{ path: "old/something/index.html" }],
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad01 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-01");
      expect(rshad01).toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-02: Worker route matches redirect source → error", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /new-page/ 301\n`,
        wranglerJsonc: JSON.stringify({
          routes: ["example.com/old-*"],
        }),
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad02 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-02");
      expect(rshad02).toBeDefined();
      expect(rshad02?.severity).toBe("error");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-02: no routes[] in wrangler.jsonc → skip", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /new-page/ 301\n`,
        wranglerJsonc: JSON.stringify({ name: "test-app" }),
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad02 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-02");
      expect(rshad02).toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-02: missing wrangler.jsonc → skip with info", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /new-page/ 301\n`,
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad02 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-02");
      expect(rshad02).toBeUndefined();
      const info = result.data!.diagnostics?.find(
        (d) => d.ruleId === "RSHAD-00" && d.severity === "info",
      );
      expect(info).toBeDefined();
      expect(info?.message).toContain("wrangler");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-02: adapter is not cloudflare-workers → skip", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /new-page/ 301\n`,
        wranglerJsonc: JSON.stringify({ routes: ["example.com/old-*"] }),
        registryYaml:
          "schemaVersion: 1.0.0\nsystems:\n  - id: test-app\n    deployment:\n      adapter: null\n",
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/new-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad02 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-02");
      expect(rshad02).toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-03: target not in sitemap + static file at target → warning", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /stale-target/ 301\n`,
        distClientFiles: [{ path: "stale-target/index.html" }],
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad03 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-03");
      expect(rshad03).toBeDefined();
      expect(rshad03?.severity).toBe("warning");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("RSHAD-03: target in sitemap → no warning", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: `${GENERATED_MARKER}/old-page /live-page/ 301\n`,
        distClientFiles: [{ path: "live-page/index.html" }],
        sitemapXml:
          '<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.com/live-page/</loc></url></urlset>',
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const rshad03 = result.data!.diagnostics?.find((d) => d.ruleId === "RSHAD-03");
      expect(rshad03).toBeUndefined();
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("missing _redirects → skip with info", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      await setupApp(root, {
        redirects: undefined,
        distClientFiles: [],
      });
      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      expect(result.data!.diagnostics).toBeDefined();
      const info = result.data!.diagnostics?.find((d) => d.severity === "info");
      expect(info).toBeDefined();
      expect(info?.message).toContain("_redirects");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("missing dist/client/ → skip with info", async () => {
    const root = await mkdtemp(join(tmpdir(), "rshad-test-"));
    try {
      const appDir = join(root, "test-app");
      const publicDir = join(appDir, "public");
      const contentDir = join(appDir, "src", "content");
      await mkdir(contentDir, { recursive: true });
      await mkdir(publicDir, { recursive: true });
      await writeFile(
        join(contentDir, "system.md"),
        "---\napp: test-app\nidentity:\n  domain: example.com\ni18n:\n  default: de\n  supported:\n    de:\n      name: Deutsch\n      hreflang: de\n---\n\n# Test",
      );
      await writeFile(join(publicDir, "_redirects"), `${GENERATED_MARKER}/old /new/ 301\n`);
      const systemsDir = join(root, "systems");
      await mkdir(systemsDir, { recursive: true });
      await writeFile(
        join(systemsDir, "registry.yaml"),
        "schemaVersion: 1.0.0\nsystems:\n  - id: test-app\n    deployment:\n      adapter: cloudflare-workers\n",
      );

      const ctx = await makeContext(root);
      const result = await runRedirectShadowValidate({} as never, ctx);
      const info = result.data!.diagnostics?.find((d) => d.severity === "info");
      expect(info).toBeDefined();
      expect(info?.message).toContain("dist/client");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
