// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: e2dda9ace888b0617acdbd535b60540b0159e9aef2334ff14058feb7b4c6c4c9
// Source: packages/ui/src/sections/navigation/navigation-section.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface NavigationSectionContent {
  label?: string;
}
