{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>Defines type declarations for Astro components and environment variables.</purpose>
<non-goals>
  <item>Do not implement runtime logic or component behavior.</item>
  <item>Do not manage application state or side effects.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Autogenerated file.</item>
</CHANGE_SUMMARY>
*/

/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

declare module "*.astro" {
  const Component: (props: Record<string, unknown>) => unknown;
  export default Component;
}

declare module "*.yaml" {
  const value: unknown;
  export default value;
}

// [RFC-0149] Astro 6 removed `Astro.locals.runtime`. Runtime secrets are read via
// `astro:env/server`; the Cloudflare `cf`/exec-context surface (if ever needed) is on
// `Astro.request.cf` / `Astro.locals.cfContext`. Do not reintroduce a `Runtime<Env>` type.
declare namespace App {
  interface Locals {
    language?: string;
  }
}
