{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>Root middleware entry point that chains all Astro request middleware.</purpose>
<non-goals>
  <item>Do not implement middleware logic here — delegate to sub-modules.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Autogenerated file.</item>
  <item>RFC-0569: chain dev-normalize middleware in dev mode for egress parity.</item>
  <item>RFC-0589: chain retired-tombstone middleware first for 410 Gone handling.</item>
  <item>RFC-0785: chain markdown-negotiation middleware for agent content negotiation.</item>
</CHANGE_SUMMARY>
*/
// @ai-invariant: High-risk module. Middleware chain. Tombstone middleware runs first, then language redirect, then markdown negotiation.
// RFC-0569: dev-normalize middleware applies egress text normalization in dev mode.
// RFC-0589: retired-tombstone middleware returns 410 Gone for retired page routes.
// RFC-0785: markdown-negotiation middleware serves .md twins for Accept: text/markdown requests.
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sequence } from "astro:middleware";
import languageRedirectMiddleware from "./middleware/language-redirect";
import tombstoneMiddleware from "./middleware/retired-tombstones";
import markdownNegotiationMiddleware from "./middleware/markdown-negotiation";
import { createDevNormalizeMiddleware, resolveNormalizeConfig } from "@warpgogol/werkstatt-site/share/text-normalize";
import { loadSystemManifestSync } from "@warpgogol/werkstatt-site/content";

const devNormalize = import.meta.env.DEV
  ? createDevNormalizeMiddleware(
      resolveNormalizeConfig(
        loadSystemManifestSync(
          resolve(dirname(fileURLToPath(import.meta.url)), "content"),
        ).manifest,
      ),
    )
  : null;

export const onRequest = import.meta.env.DEV
  ? sequence(tombstoneMiddleware, languageRedirectMiddleware, markdownNegotiationMiddleware, devNormalize!)
  : sequence(tombstoneMiddleware, languageRedirectMiddleware, markdownNegotiationMiddleware);
