import { test, expect, describe } from "vitest";
import {
  GENERATED_MARKER,
  hasGeneratedMarker,
  stripGeneratedMarker,
  buildGeneratedHeader,
  isGeneratedMarkerTextCandidate,
} from "../utils/generated-marker.ts";

describe("hasGeneratedMarker", () => {
  test("returns true when marker is present", () => {
    expect(hasGeneratedMarker(`// ${GENERATED_MARKER}`)).toBe(true);
    expect(hasGeneratedMarker(`/* ${GENERATED_MARKER} */`)).toBe(true);
  });

  test("returns false when marker is absent", () => {
    expect(hasGeneratedMarker("// some other comment")).toBe(false);
    expect(hasGeneratedMarker("")).toBe(false);
  });
});

describe("stripGeneratedMarker", () => {
  test("strips line-slash comment with marker", () => {
    const input = `// ${GENERATED_MARKER}\n// DO NOT EDIT\ncontent`;
    const result = stripGeneratedMarker(input);
    expect(result.changed).toBe(true);
    expect(result.content).not.toContain(GENERATED_MARKER);
    expect(result.content).toContain("content");
  });

  test("strips block comment with marker", () => {
    const input = `/*\n${GENERATED_MARKER}\n*/\ncontent`;
    const result = stripGeneratedMarker(input);
    expect(result.changed).toBe(true);
    expect(result.content).toBe("content");
  });

  test("strips hash comment with marker", () => {
    const input = `# ${GENERATED_MARKER}\ncontent`;
    const result = stripGeneratedMarker(input);
    expect(result.changed).toBe(true);
    expect(result.content).toBe("content");
  });

  test("strips HTML comment with marker", () => {
    const input = `<!-- ${GENERATED_MARKER} -->\ncontent`;
    const result = stripGeneratedMarker(input);
    expect(result.changed).toBe(true);
    expect(result.content).toBe("content");
  });

  test("returns unchanged when no marker", () => {
    const input = "// regular comment\ncontent";
    const result = stripGeneratedMarker(input);
    expect(result.changed).toBe(false);
    expect(result.content).toBe(input);
  });

  test("strips full header block with advisory lines", () => {
    const input = [
      `// ${GENERATED_MARKER}`,
      "// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.",
      "// Owner command: foo.generate",
      "// Edit instead: template.ts",
      "// Regenerate:   forge foo.generate",
      "",
      "actual content",
    ].join("\n");
    const result = stripGeneratedMarker(input);
    expect(result.changed).toBe(true);
    expect(result.content).not.toContain(GENERATED_MARKER);
    expect(result.content.trim()).toBe("actual content");
  });
});

describe("buildGeneratedHeader", () => {
  test("line-slash style for .ts files", () => {
    const header = buildGeneratedHeader({
      filePath: "src/generated.ts",
      ownerCommand: "foo.generate",
    });
    expect(header).toContain(`// ${GENERATED_MARKER}`);
    expect(header).toContain("// DO NOT EDIT");
    expect(header).toContain("Owner command: foo.generate");
    expect(header).toContain("Regenerate:   forge foo.generate");
    expect(header.endsWith("\n")).toBe(true);
  });

  test("line-hash style for .yml files", () => {
    const header = buildGeneratedHeader({
      filePath: "config/generated.yml",
      ownerCommand: "foo.generate",
    });
    expect(header).toContain(`# ${GENERATED_MARKER}`);
    expect(header).toContain("# DO NOT EDIT");
  });

  test("block-html style for .md files", () => {
    const header = buildGeneratedHeader({
      filePath: "docs/generated.md",
      ownerCommand: "foo.generate",
    });
    expect(header).toContain("<!--");
    expect(header).toContain(GENERATED_MARKER);
    expect(header).toContain("-->");
  });

  test("block-css style for .css files", () => {
    const header = buildGeneratedHeader({
      filePath: "styles/generated.css",
      ownerCommand: "foo.generate",
    });
    expect(header).toContain("/*");
    expect(header).toContain(GENERATED_MARKER);
    expect(header).toContain("*/");
  });

  test("includes --site when site is provided", () => {
    const header = buildGeneratedHeader({
      filePath: "src/generated.ts",
      ownerCommand: "foo.generate",
      site: "warpgogol-com",
    });
    expect(header).toContain("--site warpgogol-com");
  });

  test("uses custom commandPrefix", () => {
    const header = buildGeneratedHeader({
      filePath: "src/generated.ts",
      ownerCommand: "foo.generate",
      commandPrefix: "pnpm exec site-kernel run",
    });
    expect(header).toContain("pnpm exec site-kernel run foo.generate");
  });

  test("includes templatePath in Edit instead line", () => {
    const header = buildGeneratedHeader({
      filePath: "src/generated.ts",
      ownerCommand: "foo.generate",
      templatePath: "templates/foo.ts",
    });
    expect(header).toContain("Edit instead: templates/foo.ts");
  });
});

describe("isGeneratedMarkerTextCandidate", () => {
  test("returns true for text file extensions", () => {
    expect(isGeneratedMarkerTextCandidate("file.ts")).toBe(true);
    expect(isGeneratedMarkerTextCandidate("file.js")).toBe(true);
    expect(isGeneratedMarkerTextCandidate("file.md")).toBe(true);
    expect(isGeneratedMarkerTextCandidate("file.yml")).toBe(true);
    expect(isGeneratedMarkerTextCandidate("file.json")).toBe(true);
    expect(isGeneratedMarkerTextCandidate("file.astro")).toBe(true);
  });

  test("returns false for non-text extensions", () => {
    expect(isGeneratedMarkerTextCandidate("file.png")).toBe(false);
    expect(isGeneratedMarkerTextCandidate("file.webp")).toBe(false);
    expect(isGeneratedMarkerTextCandidate("file.mp4")).toBe(false);
  });
});
