/* 
<MODULE_CONTRACT> 
<purpose>Defines a middleware sequence for processing requests with a focus on language redirection.</purpose> 
 
 
<non-goals> 
  <item>Do not perform data validation or transformation within this middleware.</item> 
  <item>Do not manage routing or configuration settings in this context.</item> 
</non-goals> 
</MODULE_CONTRACT> 
 
<CHANGE_SUMMARY> 
  <item>Added Compass scaffolding to enhance clarity on middleware roles and boundaries.</item> 
</CHANGE_SUMMARY> 
*/

// [DNA-11] Middleware chain — ordering is fixed: language redirect runs first.
// Scaffold generated by onboarding.scaffold (RFC-0030 / DNA-36).

import { sequence } from "astro:middleware";
import languageRedirectMiddleware from "./middleware/language-redirect.js";

export const onRequest = sequence(
  // 1. Redirects / → /{detectedLang}/
  languageRedirectMiddleware,
  // Add further middleware here in dependency order.
);
