// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: props.types.generate
// Edit instead: the props.types.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run props.types.generate
// sourceHash: bc0f848a17f19901a5c64e911ccea65f9f45d78cc7c9a5d0963ecb075ac0ff59
// Source: packages/werkstatt-site/src/domain/ui/components/site-background/site-background-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface SiteBackgroundComponentContent {
  layers: unknown[];
  lang?: string;
}
