/*
<MODULE_CONTRACT>
<purpose>
RFC-0785: agent.markdown-negotiation.generate writes the Astro middleware
sub-module src/middleware/markdown-negotiation.ts that implements
Accept-header-based content negotiation for markdown twins (RFC-0166).
When agent.enabled is false, a no-op pass-through middleware is written
so the root middleware.ts import always resolves.
</purpose>
<non-goals>
  <item>Do not generate markdown twins — page.markdown.generate (RFC-0166) owns that.</item>
  <item>Do not modify the root middleware.ts — routes.generate owns that file.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0785: initial markdown negotiation middleware generator.</item>
  <item>Review fix A-1: use canonical markdownTwinUrlPath from share package, remove duplicated resolveMarkdownTwinPath.</item>
  <item>Review fix B-1: add content comparison before writing to avoid DNA-58 churn.</item>
</CHANGE_SUMMARY>
*/

import { join, dirname } from "node:path";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type {
  KernelCommandInput,
  KernelCommandResult,
  KernelRuntimeContext,
} from "@warpgogol/werkstatt/kernel";
import { requireAstroSitePaths } from "@warpgogol/werkstatt-site/paths";
import { loadSystemManifest } from "@warpgogol/werkstatt-site/content";
import { buildGeneratedHeader } from "../../codegen/generated-marker.ts";
import { readAgentBlock } from "./agent-shared.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_PATH = join(
  __dirname,
  "..",
  "..",
  "codegen",
  "templates",
  "service",
  "src",
  "middleware",
  "markdown-negotiation.ts.template",
);

const MIDDLEWARE_FILE = join("src", "middleware", "markdown-negotiation.ts");

const NOOP_CONTENT = `{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>No-op middleware — agent.enabled is false, content negotiation disabled.</purpose>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by agent.markdown-negotiation.generate (RFC-0785) — disabled mode.</item>
</CHANGE_SUMMARY>
*/

import { defineMiddleware } from "astro:middleware";

export const onRequest = defineMiddleware((_ctx, next) => next());
`;

async function writeFileIfChanged(
  context: KernelRuntimeContext,
  filePath: string,
  content: string,
): Promise<void> {
  if (await context.io.exists(filePath)) {
    const existing = await context.io.readFile(filePath);
    if (existing === content) return;
  }
  await context.io.writeFile(filePath, content);
}

export async function runAgentMarkdownNegotiationGenerate(
  _input: KernelCommandInput,
  context: KernelRuntimeContext,
): Promise<KernelCommandResult> {
  const paths = requireAstroSitePaths(context);
  const { manifest } = await loadSystemManifest(paths.contentDirectory);
  const enabled = readAgentBlock(manifest).enabled !== false;
  const languages = manifest.i18n?.supported
    ? Object.keys(manifest.i18n.supported)
    : [manifest.i18n?.default ?? "de"];
  const supportedLangsLiteral = JSON.stringify(languages);
  const middlewarePath = join(paths.appDirectory, MIDDLEWARE_FILE);

  const header = buildGeneratedHeader({
    ownerCommand: "agent.markdown-negotiation.generate",
    site: context.site?.name,
    filePath: MIDDLEWARE_FILE,
  }).trimEnd();

  if (!enabled) {
    const content = NOOP_CONTENT.replace("{{GENERATED_HEADER}}", header);
    await context.io.mkdir(join(paths.appDirectory, "src", "middleware"));
    await writeFileIfChanged(context, middlewarePath, content);
    return {
      data: {
        command: "agent.markdown-negotiation.generate",
        status: "skip",
        site: context.site?.name,
      },
      exitCode: 0,
      summary:
        "agent.markdown-negotiation.generate: skipped — agent.enabled is false (no-op middleware written)",
    };
  }

  const template = readFileSync(TEMPLATE_PATH, "utf8");
  const content = template
    .replace("{{GENERATED_HEADER}}", header)
    .replace("{{SUPPORTED_LANGS}}", supportedLangsLiteral);
  await context.io.mkdir(join(paths.appDirectory, "src", "middleware"));
  await writeFileIfChanged(context, middlewarePath, content);

  return {
    data: {
      command: "agent.markdown-negotiation.generate",
      status: "pass",
      site: context.site?.name,
      filesWritten: [MIDDLEWARE_FILE],
    },
    exitCode: 0,
    summary: context.dryRun
      ? `agent.markdown-negotiation.generate: dry-run — would write ${MIDDLEWARE_FILE}`
      : `agent.markdown-negotiation.generate: ${MIDDLEWARE_FILE}`,
  };
}
