/*
<MODULE_CONTRACT>
<purpose>
RFC-0785: agent.markdown-negotiation.generate writes the Astro middleware
sub-module src/middleware/markdown-negotiation.ts AND the custom Cloudflare
Worker entry point src/worker.ts that implements Accept-header-based content
negotiation for markdown twins (RFC-0166).
The Worker wraps the Astro Cloudflare adapter handler to intercept
Accept: text/markdown requests before matchStaticAsset short-circuits
prerendered pages (Astro issue #16252).
When agent.enabled is false, no-op pass-through files are written
so the root middleware.ts import and wrangler.jsonc main always resolve.
</purpose>
<non-goals>
  <item>Do not generate markdown twins — page.markdown.generate (RFC-0166) owns that.</item>
  <item>Do not modify the root middleware.ts — routes.generate owns that file.</item>
  <item>Do not modify wrangler.jsonc — config.regenerate owns that file.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0785: initial markdown negotiation middleware generator.</item>
  <item>Review fix A-1: use canonical markdownTwinUrlPath from share package, remove duplicated resolveMarkdownTwinPath.</item>
  <item>Review fix B-1: add content comparison before writing to avoid DNA-58 churn.</item>
  <item>Wire up src/worker.ts from worker.ts.template — wrangler.jsonc main points to src/worker.ts which wraps the Astro handler for edge content negotiation.</item>
</CHANGE_SUMMARY>
*/

import { join, dirname } from "node:path";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type {
  KernelCommandInput,
  KernelCommandResult,
  KernelRuntimeContext,
} from "@warpgogol/werkstatt/kernel";
import { requireAstroSitePaths } from "@warpgogol/werkstatt-site/paths";
import { loadSystemManifest } from "@warpgogol/werkstatt-site/content";
import { buildGeneratedHeader } from "../../codegen/generated-marker.ts";
import { readAgentBlock } from "./agent-shared.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, "..", "..", "codegen", "templates", "service", "src");
const MIDDLEWARE_TEMPLATE = join(TEMPLATES_DIR, "middleware", "markdown-negotiation.ts.template");
const WORKER_TEMPLATE = join(TEMPLATES_DIR, "worker.ts.template");

const MIDDLEWARE_FILE = join("src", "middleware", "markdown-negotiation.ts");
const WORKER_FILE = join("src", "worker.ts");

const NOOP_CONTENT = `{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>No-op middleware — agent.enabled is false, content negotiation disabled.</purpose>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by agent.markdown-negotiation.generate (RFC-0785) — disabled mode.</item>
</CHANGE_SUMMARY>
*/

import { defineMiddleware } from "astro:middleware";

export const onRequest = defineMiddleware((_ctx, next) => next());
`;

const NOOP_WORKER_CONTENT = `{{GENERATED_HEADER}}
/*
<MODULE_CONTRACT>
<purpose>No-op Worker — agent.enabled is false, pass-through to Astro handler.</purpose>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by agent.markdown-negotiation.generate (RFC-0785) — disabled mode.</item>
</CHANGE_SUMMARY>
*/

import { default as astroHandler } from "@astrojs/cloudflare/entrypoints/server";

export default {
  async fetch(request: Request, env: Record<string, unknown>, ctx: ExecutionContext): Promise<Response> {
    return astroHandler.fetch(request, env, ctx);
  },
};
`;

async function writeFileIfChanged(
  context: KernelRuntimeContext,
  filePath: string,
  content: string,
): Promise<void> {
  if (await context.io.exists(filePath)) {
    const existing = await context.io.readFile(filePath);
    if (existing === content) return;
  }
  await context.io.writeFile(filePath, content);
}

export async function runAgentMarkdownNegotiationGenerate(
  _input: KernelCommandInput,
  context: KernelRuntimeContext,
): Promise<KernelCommandResult> {
  const paths = requireAstroSitePaths(context);
  const { manifest } = await loadSystemManifest(paths.contentDirectory);
  const enabled = readAgentBlock(manifest).enabled !== false;
  const languages = manifest.i18n?.supported
    ? Object.keys(manifest.i18n.supported)
    : [manifest.i18n?.default ?? "de"];
  const supportedLangsLiteral = JSON.stringify(languages);
  const middlewarePath = join(paths.appDirectory, MIDDLEWARE_FILE);

  const middlewareHeader = buildGeneratedHeader({
    ownerCommand: "agent.markdown-negotiation.generate",
    site: context.site?.name,
    filePath: MIDDLEWARE_FILE,
  }).trimEnd();

  const workerHeader = buildGeneratedHeader({
    ownerCommand: "agent.markdown-negotiation.generate",
    site: context.site?.name,
    filePath: WORKER_FILE,
  }).trimEnd();

  const workerPath = join(paths.appDirectory, WORKER_FILE);

  if (!enabled) {
    const middlewareContent = NOOP_CONTENT.replace("{{GENERATED_HEADER}}", middlewareHeader);
    const workerContent = NOOP_WORKER_CONTENT.replace("{{GENERATED_HEADER}}", workerHeader);
    await context.io.mkdir(join(paths.appDirectory, "src", "middleware"));
    await writeFileIfChanged(context, middlewarePath, middlewareContent);
    await writeFileIfChanged(context, workerPath, workerContent);
    return {
      data: {
        command: "agent.markdown-negotiation.generate",
        status: "skip",
        site: context.site?.name,
      },
      exitCode: 0,
      summary:
        "agent.markdown-negotiation.generate: skipped — agent.enabled is false (no-op middleware + worker written)",
    };
  }

  const middlewareTemplate = readFileSync(MIDDLEWARE_TEMPLATE, "utf8");
  const middlewareContent = middlewareTemplate
    .replace("{{GENERATED_HEADER}}", middlewareHeader)
    .replace("{{SUPPORTED_LANGS}}", supportedLangsLiteral);
  await context.io.mkdir(join(paths.appDirectory, "src", "middleware"));
  await writeFileIfChanged(context, middlewarePath, middlewareContent);

  const workerTemplate = readFileSync(WORKER_TEMPLATE, "utf8");
  const workerContent = workerTemplate
    .replace("{{GENERATED_HEADER}}", workerHeader)
    .replace("{{SUPPORTED_LANGS}}", supportedLangsLiteral);
  await writeFileIfChanged(context, workerPath, workerContent);

  return {
    data: {
      command: "agent.markdown-negotiation.generate",
      status: "pass",
      site: context.site?.name,
      filesWritten: [MIDDLEWARE_FILE, WORKER_FILE],
    },
    exitCode: 0,
    summary: context.dryRun
      ? `agent.markdown-negotiation.generate: dry-run — would write ${MIDDLEWARE_FILE}, ${WORKER_FILE}`
      : `agent.markdown-negotiation.generate: ${MIDDLEWARE_FILE}, ${WORKER_FILE}`,
  };
}
