/*
<MODULE_CONTRACT>
<purpose>Kernel configuration for {{APP_NAME}} — declares modules and pipelines.</purpose>
<non-goals>
  <item>Do not add business logic or runtime behavior here.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import { defineKernelConfig } from "@gogol/site-kernel/types";
import {
  SITES_CHECK_PIPELINE,
  STANDARD_COMPASS_PIPELINE,
  SITES_BUILD_PREPARE_PIPELINE,
  SITES_BUILD_CHECK_PIPELINE,
  SITES_BUILD_POST_PIPELINE,
} from "@gogol/site-kernel-checks/pipelines";
import { STANDARD_INTEGRITY_PIPELINE } from "@gogol/site-kernel-integrity";

// moduleLoaders: each module is loaded lazily via dynamic import(), so that
// tsImport of this config file does not transitively import all module
// packages. The kernel runtime uses buildRegistryForModule() to load only
// the module that owns the requested command (manifest-driven), or
// buildRegistry() to load all modules when needed.
export default defineKernelConfig({
  name: "{{APP_NAME}}",
  description: "{{APP_NAME}} Astro site OS",
  moduleLoaders: {
    check: async () => (await import("./modules/check.module")).checkModule,
    service: async () => (await import("./modules/service.module")).serviceModule,
    deploy: async () => (await import("./modules/deploy.module")).deployModule,
    integrity: async () => (await import("./modules/integrity.module")).integrityModule,
    changelog: async () => (await import("./modules/changelog.module")).changelogModule,
    rfc: async () => (await import("@webgogol/forge")).forgeRfcModule,
    workflow: async () => (await import("@webgogol/forge")).forgeWorkflowModule,
    compass: async () => (await import("@webgogol/forge")).forgeCompassModule,
    naming: async () => (await import("@webgogol/forge")).forgeNamingModule,
    werkstatt: async () => (await import("@webgogol/forge")).forgeWerkstattModule,
    lagebild: async () => (await import("@gogol/site-kernel")).lagebildModule,
    "change-impact": async () => (await import("@gogol/site-kernel")).changeImpactModule,
    bordbuch: async () =>
      (await import("@gogol/site-kernel-handoff")).createBordbuchModule(),
    onboarding: async () =>
      (await import("@gogol/site-kernel-onboarding")).createOnboardingModule(),
  },
  pipelines: {
    "build.prepare": [...SITES_BUILD_PREPARE_PIPELINE],
    "build.check": [...SITES_BUILD_CHECK_PIPELINE],
    "build.post": [...SITES_BUILD_POST_PIPELINE],
    check: [...SITES_CHECK_PIPELINE],
    compass: [...STANDARD_COMPASS_PIPELINE],
    "integrity.release": [...STANDARD_INTEGRITY_PIPELINE],
  },
});
