// GENERATED. Do not change this line unless the file contains project specific changes.
// sourceHash: 896845a66b04a60f7c58801a903c772b721c28afacb517e8f0590b412c2f3b40
// Source: packages/ui/src/components/copyright/copyright-component.manifest.yaml
// Generated by: props.types.generate (RFC-0262). Do not hand-edit — edit the manifest propsSchema and regenerate.

export interface CopyrightComponentContent {
  copyright: {
    symbol?: string;
    yearFirst: number;
    yearSecond?: number;
    holder: string;
    suffix?: string;
  };
}
